In [1]:
# prompt: mount drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
#Loading the hindi dataset
file_path  = "/content/drive/MyDrive/ML_sem2/stemmed_hindi.csv"
df_hindi = pd.read_csv(file_path)
print(len(df_hindi))

6400

In [3]:
df_hindi_01 = df_hindi.drop(df_hindi.columns[0], axis=1)

In [4]:
df_hindi = df_hindi_01
df_hindi

,Sentence,anger,disgust,fear,joy,neutral,sadness,surprise
0,कहना कि यह बारे पूरा तरह खुश,False,False,False,False,False,False,True
1,ठीक ठीक देखना जानना कि आज श्री अनुपयुक्त होना ...,False,False,False,True,False,False,False
2,ओह वह एक रहना,False,False,False,True,False,False,False
3,सब तुम कारण अद्भुत अद्भुत,False,False,False,True,False,False,False
4,जानना जानना भयभीत होना जाना भयभीत होना जाना वह...,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...
6395,साल का,False,False,False,False,True,False,False
6396,कौन होना,True,False,False,False,False,False,False
6397,तुम अपना जीवन जोखिम डालना एक सैंडविच लेना,False,False,False,True,False,False,False
6398,महान,False,False,False,True,False,False,False
6399,वह लड़की जानना होना जो बारे मैं तुम बताना था ज...,False,False,False,False,True,False,False

In [5]:
emotion_columns_h = ['anger', 'disgust', 'fear', 'joy', 'neutral', 'sadness', 'surprise',]

In [6]:
df_hindi['Emotion'] = df_hindi[emotion_columns_h].idxmax(axis=1)

In [7]:
df_hindi = df_hindi[['Sentence', 'Emotion']]

In [8]:
# prompt: Rename the col name in df

df_hindi = df_hindi.rename(columns={'Sentence': 'text'})

In [9]:
df_hindi

                                                   text   Emotion
0                          कहना कि यह बारे पूरा तरह खुश  surprise
1     ठीक ठीक देखना जानना कि आज श्री अनुपयुक्त होना ...       joy
2                                         ओह वह एक रहना       joy
3                             सब तुम कारण अद्भुत अद्भुत       joy
4     जानना जानना भयभीत होना जाना भयभीत होना जाना वह...  surprise
...                                                 ...       ...
6395                                             साल का   neutral
6396                                           कौन होना     anger
6397          तुम अपना जीवन जोखिम डालना एक सैंडविच लेना       joy
6398                                               महान       joy
6399  वह लड़की जानना होना जो बारे मैं तुम बताना था ज...   neutral

[6400 rows x 2 columns]

In [10]:
if df_hindi.isnull().values.any():
    print("There are NaN values in the DataFrame.")
    print(df_hindi.isnull().sum())
    df_hindi.dropna(inplace=True)
    print("removed")# This will print the number of NaNs in each column
else:
    print("No NaN values found in the DataFrame.")

There are NaN values in the DataFrame.
text       143
Emotion      0
dtype: int64
removed

In [14]:
df_hindi

                                                   text   Emotion
0                          कहना कि यह बारे पूरा तरह खुश  surprise
1     ठीक ठीक देखना जानना कि आज श्री अनुपयुक्त होना ...       joy
2                                         ओह वह एक रहना       joy
3                             सब तुम कारण अद्भुत अद्भुत       joy
4     जानना जानना भयभीत होना जाना भयभीत होना जाना वह...  surprise
...                                                 ...       ...
6395                                             साल का   neutral
6396                                           कौन होना     anger
6397          तुम अपना जीवन जोखिम डालना एक सैंडविच लेना       joy
6398                                               महान       joy
6399  वह लड़की जानना होना जो बारे मैं तुम बताना था ज...   neutral

[6257 rows x 2 columns]

In [15]:
import pandas as pd
#Loading the hindi dataset
file_path  = "/content/drive/MyDrive/ML_sem2/stemmed_eng1.csv"
df_english = pd.read_csv(file_path)
print(len(df_english))

10983

In [16]:
df_english

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,worry payment problem may never joyce meyer,False,True,False,False,False,False,True,False,False,False,True
1,whatever decide make sure make,False,False,False,False,True,True,True,False,False,False,False
2,also help majority nfl coaching inept bill obr...,True,False,True,False,True,False,True,False,False,False,False
3,accept challenge literally even feel exhilarat...,False,False,False,False,True,False,True,False,False,False,False
4,roommate okay cant spell autocorrect,True,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
10978,do not make angry id laugh tweet,True,False,True,False,False,False,False,False,False,False,False
10979,excited watch tonight come NSw,False,False,False,False,True,False,True,False,False,False,False
10980,blah blah blah kyrie etc. leave boston real news,True,False,True,False,False,False,False,False,True,False,False
10981,wise never trust flock wolf,False,False,False,False,False,False,False,False,False,False,False
10982,really flatter happy hear complement blog guy ...,False,False,False,False,True,False,True,False,False,False,False

In [17]:
emotion_columns_e = ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust']

In [18]:
df_english['Emotion'] = df_english[emotion_columns_e].idxmax(axis=1)

In [19]:
df_english = df_english[['Tweet', 'Emotion']]

In [20]:
# prompt: Rename the col name in df

df_english= df_english.rename(columns={'Tweet': 'text'})

In [21]:
df_english

                                                    text       Emotion
0            worry payment problem may never joyce meyer  anticipation
1                         whatever decide make sure make           joy
2      also help majority nfl coaching inept bill obr...         anger
3      accept challenge literally even feel exhilarat...           joy
4                   roommate okay cant spell autocorrect         anger
...                                                  ...           ...
10978                   do not make angry id laugh tweet         anger
10979                     excited watch tonight come NSw           joy
10980   blah blah blah kyrie etc. leave boston real news         anger
10981                        wise never trust flock wolf         anger
10982  really flatter happy hear complement blog guy ...           joy

[10983 rows x 2 columns]

In [22]:
if df_english.isnull().values.any():
    print("There are NaN values in the DataFrame.")
    print(df_english.isnull().sum())
    df_english.dropna(inplace=True)
    print("removed")# This will print the number of NaNs in each column
else:
    print("No NaN values found in the DataFrame.")

There are NaN values in the DataFrame.
text       25
Emotion     0
dtype: int64
removed

In [26]:
df_english

                                                    text       Emotion
0            worry payment problem may never joyce meyer  anticipation
1                         whatever decide make sure make           joy
2      also help majority nfl coaching inept bill obr...         anger
3      accept challenge literally even feel exhilarat...           joy
4                   roommate okay cant spell autocorrect         anger
...                                                  ...           ...
10978                   do not make angry id laugh tweet         anger
10979                     excited watch tonight come NSw           joy
10980   blah blah blah kyrie etc. leave boston real news         anger
10981                        wise never trust flock wolf         anger
10982  really flatter happy hear complement blog guy ...           joy

[10958 rows x 2 columns]

In [27]:
import pandas as pd
#Loading the hindi dataset
file_path  = "/content/drive/MyDrive/ML_sem2/stemmed_spanish.csv"
df_spanish = pd.read_csv(file_path)
print(len(df_spanish))

5675

In [28]:
df_spanish = df_spanish.drop(df_spanish.columns[0], axis=1)

In [29]:
df_spanish

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,detrs horrible desagradable ir ver él cerr ojo...,False,False,True,True,False,False,False,False,False,False,False
1,gustar idea solitario a ec arrasar louis gloria,True,False,False,False,True,False,False,False,False,False,False
2,comn menos comn,False,False,False,False,False,False,False,False,False,False,False
3,s pequeo minifundista mundo saber recibir fond...,True,False,True,False,False,False,False,False,False,False,False
4,empezar sonar alarma corte sirena tener llamar...,True,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
5670,hora respiracin empezar enloquecer,False,False,False,False,False,False,False,False,False,False,False
5671,ojo entender preocupacin realmente piba volver...,True,False,False,False,False,False,False,True,False,False,False
5672,miedo perder afortunado tener,False,False,False,True,False,False,True,False,True,False,False
5673,broma jams enojo l siempre coger dm,True,False,False,False,True,False,True,False,False,False,False
5674,fome nose re igual,False,False,False,False,True,False,False,False,False,False,False

In [30]:

emotion_columns_s = ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust']

In [31]:
df_spanish['Emotion'] = df_spanish[emotion_columns_s].idxmax(axis=1)

In [32]:
df_spanish = df_spanish[['Tweet', 'Emotion']]

In [33]:
# prompt: rename col in df

df_spanish = df_spanish.rename(columns={'Tweet': 'text'})
df_spanish

                                                   text  Emotion
0     detrs horrible desagradable ir ver él cerr ojo...  disgust
1       gustar idea solitario a ec arrasar louis gloria    anger
2                                       comn menos comn    anger
3     s pequeo minifundista mundo saber recibir fond...    anger
4     empezar sonar alarma corte sirena tener llamar...    anger
...                                                 ...      ...
5670                 hora respiracin empezar enloquecer    anger
5671  ojo entender preocupacin realmente piba volver...    anger
5672                      miedo perder afortunado tener     fear
5673                broma jams enojo l siempre coger dm    anger
5674                                 fome nose re igual      joy

[5675 rows x 2 columns]

In [34]:
if df_spanish.isnull().values.any():
    print("There are NaN values in the DataFrame.")
    print(df_spanish.isnull().sum())
    df_spanish.dropna(inplace=True)
    print("removed")# This will print the number of NaNs in each column
else:
    print("No NaN values found in the DataFrame.")

There are NaN values in the DataFrame.
text       10
Emotion     0
dtype: int64
removed

In [38]:
df_spanish

                                                   text  Emotion
0     detrs horrible desagradable ir ver él cerr ojo...  disgust
1       gustar idea solitario a ec arrasar louis gloria    anger
2                                       comn menos comn    anger
3     s pequeo minifundista mundo saber recibir fond...    anger
4     empezar sonar alarma corte sirena tener llamar...    anger
...                                                 ...      ...
5670                 hora respiracin empezar enloquecer    anger
5671  ojo entender preocupacin realmente piba volver...    anger
5672                      miedo perder afortunado tener     fear
5673                broma jams enojo l siempre coger dm    anger
5674                                 fome nose re igual      joy

[5665 rows x 2 columns]

In [39]:
# prompt: concat three df

combined_df = pd.concat([df_hindi, df_english, df_spanish], ignore_index=True)
combined_df

                                                    text   Emotion
0                           कहना कि यह बारे पूरा तरह खुश  surprise
1      ठीक ठीक देखना जानना कि आज श्री अनुपयुक्त होना ...       joy
2                                          ओह वह एक रहना       joy
3                              सब तुम कारण अद्भुत अद्भुत       joy
4      जानना जानना भयभीत होना जाना भयभीत होना जाना वह...  surprise
...                                                  ...       ...
22875                 hora respiracin empezar enloquecer     anger
22876  ojo entender preocupacin realmente piba volver...     anger
22877                      miedo perder afortunado tener      fear
22878                broma jams enojo l siempre coger dm     anger
22879                                 fome nose re igual       joy

[22880 rows x 2 columns]

In [41]:
if combined_df.isnull().values.any():
    print("There are NaN values in the DataFrame.")
    print(combined_df.isnull().sum())  # This will print the number of NaNs in each column
else:
    print("No NaN values found in the DataFrame.")

No NaN values found in the DataFrame.

In [42]:
combined_df.dropna(inplace=True)

In [43]:
import torch

In [44]:
# Replace `df` with your DataFrame and `column_name` with the name of your column
distinct_labels = combined_df['Emotion'].unique()
print(distinct_labels)

['surprise' 'joy' 'neutral' 'fear' 'disgust' 'sadness' 'anger'
 'anticipation' 'optimism' 'love' 'pessimism' 'trust']

In [45]:
# Load your dataset
df = combined_df  # Ensure this DataFrame is defined correctly

# Map emotions to integers
label_mapping = {
    'anger': 0, 'anticipation': 1, 'disgust': 2, 'fear': 3,
    'joy': 4, 'love': 5, 'optimism': 6, 'pessimism': 7,
    'sadness': 8, 'surprise': 9, 'trust': 10, 'neutral': 11
}
df['Emotion'] = df['Emotion'].map(label_mapping)

# Check unique values after mapping
print("Unique values in Emotion column after mapping:", df['Emotion'].unique())

# Ensure there are no NaN values after mapping
if df['Emotion'].isnull().any():
    print("NaN values found in Emotion column after mapping. Please check the mapping.")

# Drop duplicates
df.drop_duplicates(subset='text', inplace=True)

Unique values in Emotion column after mapping: [ 9  4 11  3  2  8  0  1  6  5  7 10]

In [46]:
from sklearn.model_selection import train_test_split
# Split data into training and validation sets
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['text'].tolist(),
    df['Emotion'].tolist(),
    test_size=0.2,
    random_state=42
)

In [40]:
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np


# Tokenizer initialization for mBERT
tokenizer = BertTokenizer.from_pretrained('distilbert-base-multilingual-cased')

# Tokenize the data
def tokenize_function(texts):
    return tokenizer(texts, padding=True, truncation=True, return_tensors='pt', max_length=512)

# Remove NaN and empty texts
train_texts = [text for text in train_texts if isinstance(text, str) and text.strip() != ""]

# Tokenize
train_encodings = tokenize_function(train_texts)
val_encodings = tokenize_function(val_texts)

# Custom Dataset class for PyTorch
class EmotionDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx].clone().detach() for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(int(self.labels[idx]), dtype=torch.long)  # Ensure labels are of type long
        return item

# Create the Dataset objects
train_dataset = EmotionDataset(train_encodings, train_labels)
val_dataset = EmotionDataset(val_encodings, val_labels)



# Model initialization for mBERT
model = BertForSequenceClassification.from_pretrained('distilbert-base-multilingual-cased', num_labels=len(label_mapping))

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',
    learning_rate=2e-5,
    num_train_epochs=10,              # Reduced number of epochs
    per_device_train_batch_size=32,   # Reduced batch size
    per_device_eval_batch_size=32,
    warmup_steps=500,
    weight_decay=0.1,
    logging_dir='./logs',
    eval_strategy="epoch",
    save_strategy="epoch",
    fp16=True,                       # Enable mixed precision training
)

# Create Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()
print(eval_results)

# Detailed evaluation metrics
preds = trainer.predict(val_dataset)
y_pred = np.argmax(preds.predictions, axis=1)
print(classification_report(val_labels, y_pred, target_names=list(label_mapping.keys())))
#0860061c9c63c88d713a4e8fcf51011aca94aa50

Unique values in Emotion column after mapping: [ 9  4 11  3  2  8  0  1  6  5  7 10]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/466 [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization.
The tokenizer class you load from this checkpoint is 'DistilBertTokenizer'.
The class this function is called from is 'BertTokenizer'.
You are using a model of type distilbert to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.

model.safetensors:   0%|          | 0.00/542M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight', 'embeddings.LayerNorm.bias', 'embeddings.LayerNorm.weight', 'embeddings.position_embeddings.weight', 'embeddings.token_type_embeddings.weight', 'embeddings.word_embeddings.weight', 'encoder.layer.0.attention.output.LayerNorm.bias', 'encoder.layer.0.attention.output.LayerNorm.weight', 'encoder.layer.0.attention.output.dense.bias', 'encoder.layer.0.attention.output.dense.weight', 'encoder.layer.0.attention.self.key.bias', 'encoder.layer.0.attention.self.key.weight', 'encoder.layer.0.attention.self.query.bias', 'encoder.layer.0.attention.self.query.weight', 'encoder.layer.0.attention.self.value.bias', 'encoder.layer.0.attention.self.value.weight', 'encoder.layer.0.intermediate.dense.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.0.output.LayerNorm.bias', 'encoder.layer.0.output.LayerNorm.weight', 'encoder.layer.0.output.dense.bias', 'encoder.layer.0.output.dense.weight', 'encoder.layer.1.attention.output.LayerNorm.bias', 'encoder.layer.1.attention.output.LayerNorm.weight', 'encoder.layer.1.attention.output.dense.bias', 'encoder.layer.1.attention.output.dense.weight', 'encoder.layer.1.attention.self.key.bias', 'encoder.layer.1.attention.self.key.weight', 'encoder.layer.1.attention.self.query.bias', 'encoder.layer.1.attention.self.query.weight', 'encoder.layer.1.attention.self.value.bias', 'encoder.layer.1.attention.self.value.weight', 'encoder.layer.1.intermediate.dense.bias', 'encoder.layer.1.intermediate.dense.weight', 'encoder.layer.1.output.LayerNorm.bias', 'encoder.layer.1.output.LayerNorm.weight', 'encoder.layer.1.output.dense.bias', 'encoder.layer.1.output.dense.weight', 'encoder.layer.10.attention.output.LayerNorm.bias', 'encoder.layer.10.attention.output.LayerNorm.weight', 'encoder.layer.10.attention.output.dense.bias', 'encoder.layer.10.attention.output.dense.weight', 'encoder.layer.10.attention.self.key.bias', 'encoder.layer.10.attention.self.key.weight', 'encoder.layer.10.attention.self.query.bias', 'encoder.layer.10.attention.self.query.weight', 'encoder.layer.10.attention.self.value.bias', 'encoder.layer.10.attention.self.value.weight', 'encoder.layer.10.intermediate.dense.bias', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.10.output.LayerNorm.bias', 'encoder.layer.10.output.LayerNorm.weight', 'encoder.layer.10.output.dense.bias', 'encoder.layer.10.output.dense.weight', 'encoder.layer.11.attention.output.LayerNorm.bias', 'encoder.layer.11.attention.output.LayerNorm.weight', 'encoder.layer.11.attention.output.dense.bias', 'encoder.layer.11.attention.output.dense.weight', 'encoder.layer.11.attention.self.key.bias', 'encoder.layer.11.attention.self.key.weight', 'encoder.layer.11.attention.self.query.bias', 'encoder.layer.11.attention.self.query.weight', 'encoder.layer.11.attention.self.value.bias', 'encoder.layer.11.attention.self.value.weight', 'encoder.layer.11.intermediate.dense.bias', 'encoder.layer.11.intermediate.dense.weight', 'encoder.layer.11.output.LayerNorm.bias', 'encoder.layer.11.output.LayerNorm.weight', 'encoder.layer.11.output.dense.bias', 'encoder.layer.11.output.dense.weight', 'encoder.layer.2.attention.output.LayerNorm.bias', 'encoder.layer.2.attention.output.LayerNorm.weight', 'encoder.layer.2.attention.output.dense.bias', 'encoder.layer.2.attention.output.dense.weight', 'encoder.layer.2.attention.self.key.bias', 'encoder.layer.2.attention.self.key.weight', 'encoder.layer.2.attention.self.query.bias', 'encoder.layer.2.attention.self.query.weight', 'encoder.layer.2.attention.self.value.bias', 'encoder.layer.2.attention.self.value.weight', 'encoder.layer.2.intermediate.dense.bias', 'encoder.layer.2.intermediate.dense.weight', 'encoder.layer.2.output.LayerNorm.bias', 'encoder.layer.2.output.LayerNorm.weight', 'encoder.layer.2.output.dense.bias', 'encoder.layer.2.output.dense.weight', 'encoder.layer.3.attention.output.LayerNorm.bias', 'encoder.layer.3.attention.output.LayerNorm.weight', 'encoder.layer.3.attention.output.dense.bias', 'encoder.layer.3.attention.output.dense.weight', 'encoder.layer.3.attention.self.key.bias', 'encoder.layer.3.attention.self.key.weight', 'encoder.layer.3.attention.self.query.bias', 'encoder.layer.3.attention.self.query.weight', 'encoder.layer.3.attention.self.value.bias', 'encoder.layer.3.attention.self.value.weight', 'encoder.layer.3.intermediate.dense.bias', 'encoder.layer.3.intermediate.dense.weight', 'encoder.layer.3.output.LayerNorm.bias', 'encoder.layer.3.output.LayerNorm.weight', 'encoder.layer.3.output.dense.bias', 'encoder.layer.3.output.dense.weight', 'encoder.layer.4.attention.output.LayerNorm.bias', 'encoder.layer.4.attention.output.LayerNorm.weight', 'encoder.layer.4.attention.output.dense.bias', 'encoder.layer.4.attention.output.dense.weight', 'encoder.layer.4.attention.self.key.bias', 'encoder.layer.4.attention.self.key.weight', 'encoder.layer.4.attention.self.query.bias', 'encoder.layer.4.attention.self.query.weight', 'encoder.layer.4.attention.self.value.bias', 'encoder.layer.4.attention.self.value.weight', 'encoder.layer.4.intermediate.dense.bias', 'encoder.layer.4.intermediate.dense.weight', 'encoder.layer.4.output.LayerNorm.bias', 'encoder.layer.4.output.LayerNorm.weight', 'encoder.layer.4.output.dense.bias', 'encoder.layer.4.output.dense.weight', 'encoder.layer.5.attention.output.LayerNorm.bias', 'encoder.layer.5.attention.output.LayerNorm.weight', 'encoder.layer.5.attention.output.dense.bias', 'encoder.layer.5.attention.output.dense.weight', 'encoder.layer.5.attention.self.key.bias', 'encoder.layer.5.attention.self.key.weight', 'encoder.layer.5.attention.self.query.bias', 'encoder.layer.5.attention.self.query.weight', 'encoder.layer.5.attention.self.value.bias', 'encoder.layer.5.attention.self.value.weight', 'encoder.layer.5.intermediate.dense.bias', 'encoder.layer.5.intermediate.dense.weight', 'encoder.layer.5.output.LayerNorm.bias', 'encoder.layer.5.output.LayerNorm.weight', 'encoder.layer.5.output.dense.bias', 'encoder.layer.5.output.dense.weight', 'encoder.layer.6.attention.output.LayerNorm.bias', 'encoder.layer.6.attention.output.LayerNorm.weight', 'encoder.layer.6.attention.output.dense.bias', 'encoder.layer.6.attention.output.dense.weight', 'encoder.layer.6.attention.self.key.bias', 'encoder.layer.6.attention.self.key.weight', 'encoder.layer.6.attention.self.query.bias', 'encoder.layer.6.attention.self.query.weight', 'encoder.layer.6.attention.self.value.bias', 'encoder.layer.6.attention.self.value.weight', 'encoder.layer.6.intermediate.dense.bias', 'encoder.layer.6.intermediate.dense.weight', 'encoder.layer.6.output.LayerNorm.bias', 'encoder.layer.6.output.LayerNorm.weight', 'encoder.layer.6.output.dense.bias', 'encoder.layer.6.output.dense.weight', 'encoder.layer.7.attention.output.LayerNorm.bias', 'encoder.layer.7.attention.output.LayerNorm.weight', 'encoder.layer.7.attention.output.dense.bias', 'encoder.layer.7.attention.output.dense.weight', 'encoder.layer.7.attention.self.key.bias', 'encoder.layer.7.attention.self.key.weight', 'encoder.layer.7.attention.self.query.bias', 'encoder.layer.7.attention.self.query.weight', 'encoder.layer.7.attention.self.value.bias', 'encoder.layer.7.attention.self.value.weight', 'encoder.layer.7.intermediate.dense.bias', 'encoder.layer.7.intermediate.dense.weight', 'encoder.layer.7.output.LayerNorm.bias', 'encoder.layer.7.output.LayerNorm.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.7.output.dense.weight', 'encoder.layer.8.attention.output.LayerNorm.bias', 'encoder.layer.8.attention.output.LayerNorm.weight', 'encoder.layer.8.attention.output.dense.bias', 'encoder.layer.8.attention.output.dense.weight', 'encoder.layer.8.attention.self.key.bias', 'encoder.layer.8.attention.self.key.weight', 'encoder.layer.8.attention.self.query.bias', 'encoder.layer.8.attention.self.query.weight', 'encoder.layer.8.attention.self.value.bias', 'encoder.layer.8.attention.self.value.weight', 'encoder.layer.8.intermediate.dense.bias', 'encoder.layer.8.intermediate.dense.weight', 'encoder.layer.8.output.LayerNorm.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.8.output.dense.bias', 'encoder.layer.8.output.dense.weight', 'encoder.layer.9.attention.output.LayerNorm.bias', 'encoder.layer.9.attention.output.LayerNorm.weight', 'encoder.layer.9.attention.output.dense.bias', 'encoder.layer.9.attention.output.dense.weight', 'encoder.layer.9.attention.self.key.bias', 'encoder.layer.9.attention.self.key.weight', 'encoder.layer.9.attention.self.query.bias', 'encoder.layer.9.attention.self.query.weight', 'encoder.layer.9.attention.self.value.bias', 'encoder.layer.9.attention.self.value.weight', 'encoder.layer.9.intermediate.dense.bias', 'encoder.layer.9.intermediate.dense.weight', 'encoder.layer.9.output.LayerNorm.bias', 'encoder.layer.9.output.LayerNorm.weight', 'encoder.layer.9.output.dense.bias', 'encoder.layer.9.output.dense.weight', 'pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

{'eval_loss': 1.7745023965835571, 'eval_runtime': 4.1578, 'eval_samples_per_second': 1013.27, 'eval_steps_per_second': 31.747, 'epoch': 10.0}
              precision    recall  f1-score   support

       anger       0.58      0.60      0.59      1249
anticipation       0.21      0.22      0.22       339
     disgust       0.07      0.03      0.05       203
        fear       0.42      0.33      0.37       263
         joy       0.57      0.56      0.57      1058
        love       0.00      0.00      0.00        37
    optimism       0.13      0.06      0.08        68
   pessimism       0.18      0.12      0.14       133
     sadness       0.39      0.20      0.26       214
    surprise       0.43      0.23      0.30       137
       trust       0.00      0.00      0.00         2
     neutral       0.50      0.89      0.64       510

    accuracy                           0.49      4213
   macro avg       0.29      0.27      0.27      4213
weighted avg       0.46      0.49      0.47      4213

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [41]:
from sklearn.metrics import accuracy_score

#val_dataset = EmotionDataset(val_encodings, val_labels)
# Get predictions
predictions = trainer.predict(EmotionDataset(val_encodings, val_labels))

# Convert logits to predicted labels (if necessary)
predicted_labels = np.argmax(predictions.predictions, axis=1)

# Calculate accuracy
accuracy = accuracy_score(val_labels, predicted_labels)  # Ensure val_labels are defined
print("Manual Accuracy:", accuracy)

Manual Accuracy: 0.4892000949442203

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np

# Load your dataset


# Tokenizer initialization for mBERT
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

# Tokenize the data
def tokenize_function(texts):
    return tokenizer(texts, padding=True, truncation=True, return_tensors='pt', max_length=512)

# Remove NaN and empty texts
train_texts = [text for text in train_texts if isinstance(text, str) and text.strip() != ""]

# Tokenize
train_encodings = tokenize_function(train_texts)
val_encodings = tokenize_function(val_texts)

# Custom Dataset class for PyTorch
class EmotionDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx].clone().detach() for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(int(self.labels[idx]), dtype=torch.long)  # Ensure labels are of type long
        return item

# Create the Dataset objects
train_dataset = EmotionDataset(train_encodings, train_labels)
val_dataset = EmotionDataset(val_encodings, val_labels)

# Model initialization for mBERT
model = BertForSequenceClassification.from_pretrained('bert-base-multilingual-cased', num_labels=len(label_mapping))

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',
     learning_rate=2e-5,
    num_train_epochs=10,              # Reduced number of epochs
    per_device_train_batch_size=32,   # Reduced batch size
    per_device_eval_batch_size=32,
    warmup_steps=500,
    weight_decay=0.1,
    logging_dir='./logs',
    eval_strategy="epoch",
    save_strategy="epoch",
    fp16=True,                       # Enable mixed precision training
)

# Create Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()
print(eval_results)

# Detailed evaluation metrics
preds = trainer.predict(val_dataset)
y_pred = np.argmax(preds.predictions, axis=1)
print(classification_report(val_labels, y_pred, target_names=list(label_mapping.keys())))

In [44]:
import torch
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from transformers import get_linear_schedule_with_warmup
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import pandas as pd
import numpy as np
from transformers import EarlyStoppingCallback


# Tokenizer initialization for mBERT
tokenizer = BertTokenizer.from_pretrained('bert-base-multilingual-cased')

# Tokenization function with truncation and padding
def tokenize_function(texts):
    return tokenizer(texts, padding=True, truncation=True, max_length=256, return_tensors='pt')

# Tokenize the data
train_encodings = tokenize_function(train_texts)
val_encodings = tokenize_function(val_texts)

# Custom Dataset class for PyTorch
class EmotionDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx].clone().detach() for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

# Create Dataset objects
train_dataset = EmotionDataset(train_encodings, train_labels)
val_dataset = EmotionDataset(val_encodings, val_labels)

# Model initialization with increased dropout
model = BertForSequenceClassification.from_pretrained('bert-base-multilingual-cased', num_labels=len(label_mapping))
model.config.hidden_dropout_prob = 0.3
model.config.attention_probs_dropout_prob = 0.3

# Training arguments with load_best_model_at_end and save strategy set to "epoch"
training_args = TrainingArguments(
    output_dir='./results',
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=1e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=10,
    weight_decay=0.1,
    warmup_steps=1000,
    logging_dir='./logs',
    logging_steps=50,
    fp16=True,
    load_best_model_at_end=True,
    gradient_accumulation_steps=2,
    label_smoothing_factor=0.1,
    max_grad_norm=1.0,
)

# Instantiate the Trainer with early stopping callback
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]  # Stop after 2 epochs of no improvement
)

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()
print("Evaluation Results:", eval_results)

# Detailed evaluation metrics
preds = trainer.predict(val_dataset)
y_pred = np.argmax(preds.predictions, axis=1)
print(classification_report(val_labels, y_pred, target_names=list(label_mapping.keys())))


#0860061c9c63c88d713a4e8fcf51011aca94aa50

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/49.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/996k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.96M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/625 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/714M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-multilingual-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

Evaluation Results: {'eval_loss': 1.667211890220642, 'eval_runtime': 5.1989, 'eval_samples_per_second': 810.36, 'eval_steps_per_second': 50.78, 'epoch': 6.0}
              precision    recall  f1-score   support

       anger       0.60      0.73      0.66      1299
anticipation       0.25      0.12      0.16       333
     disgust       0.00      0.00      0.00       207
        fear       0.48      0.35      0.40       260
         joy       0.58      0.64      0.61      1010
        love       0.00      0.00      0.00        30
    optimism       1.00      0.01      0.03        68
   pessimism       0.18      0.02      0.03       117
     sadness       0.41      0.21      0.28       213
    surprise       0.35      0.06      0.10       136
       trust       0.00      0.00      0.00         4
     neutral       0.50      0.93      0.65       536

    accuracy                           0.54      4213
   macro avg       0.36      0.26      0.24      4213
weighted avg       0.49      0.54      0.49      4213

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [45]:
from sklearn.metrics import accuracy_score

# Get predictions
predictions = trainer.predict(val_dataset)

# Convert logits to predicted labels (if necessary)
predicted_labels = np.argmax(predictions.predictions, axis=1)

# Calculate accuracy
accuracy = accuracy_score(val_labels, predicted_labels)  # Ensure val_labels are defined
print("Manual Accuracy:", accuracy)

Manual Accuracy: 0.5418941371943983

In [ ]:
import pandas as pd
from transformers import XLMRobertaTokenizer, XLMRobertaForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset
import torch

# Load the tokenizer and model
tokenizer = XLMRobertaTokenizer.from_pretrained("xlm-roberta-base")
model = XLMRobertaForSequenceClassification.from_pretrained("xlm-roberta-base", num_labels=12)  # Change num_labels as per your emotion classes

# Define a custom dataset
class EmotionDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len=128):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        encoding = self.tokenizer.encode_plus(
            text,
            max_length=self.max_len,
            padding="max_length",
            truncation=True,
            return_tensors="pt"
        )

        return {
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'labels': torch.tensor(label, dtype=torch.long)
        }

# Create Dataset objects
train_dataset = EmotionDataset(train_texts, train_labels, tokenizer)
val_dataset = EmotionDataset(val_texts, val_labels, tokenizer)

# Define training arguments
training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=10,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs',
    evaluation_strategy="epoch"
)

# Create Trainer instance
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset
)

# Train the model
trainer.train()

# Save the model
model.save_pretrained("emotion_model")
tokenizer.save_pretrained("emotion_model")
#0860061c9c63c88d713a4e8fcf51011aca94aa50

Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at xlm-roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/usr/local/lib/python3.10/dist-packages/transformers/training_args.py:1568: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(