In [1]:
!pip install datasets

Requirement already satisfied: datasets in e:\conda\lib\site-packages (3.0.1)
Requirement already satisfied: filelock in e:\conda\lib\site-packages (from datasets) (3.13.1)
Requirement already satisfied: numpy>=1.17 in e:\conda\lib\site-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in e:\conda\lib\site-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in e:\conda\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in e:\conda\lib\site-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in e:\conda\lib\site-packages (from datasets) (2.32.2)
Requirement already satisfied: tqdm>=4.66.3 in e:\conda\lib\site-packages (from datasets) (4.66.4)
Requirement already satisfied: xxhash in e:\conda\lib\site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in e:\conda\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.6.1,>=2023.1.0 in e:\conda\lib\site-packages (from fsspec[http]<=2024.6.1,>=2023.1.0->datasets) (2024.3.1)
Requirement already satisfied: aiohttp in e:\conda\lib\site-packages (from datasets) (3.9.5)
Requirement already satisfied: huggingface-hub>=0.22.0 in e:\conda\lib\site-packages (from datasets) (0.25.1)
Requirement already satisfied: packaging in e:\conda\lib\site-packages (from datasets) (23.2)
Requirement already satisfied: pyyaml>=5.1 in e:\conda\lib\site-packages (from datasets) (6.0.1)
Requirement already satisfied: aiosignal>=1.1.2 in e:\conda\lib\site-packages (from aiohttp->datasets) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in e:\conda\lib\site-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in e:\conda\lib\site-packages (from aiohttp->datasets) (1.4.0)
Requirement already satisfied: multidict<7.0,>=4.5 in e:\conda\lib\site-packages (from aiohttp->datasets) (6.0.4)
Requirement already satisfied: yarl<2.0,>=1.0 in e:\conda\lib\site-packages (from aiohttp->datasets) (1.9.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in e:\conda\lib\site-packages (from huggingface-hub>=0.22.0->datasets) (4.11.0)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\conda\lib\site-packages (from requests>=2.32.2->datasets) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in e:\conda\lib\site-packages (from requests>=2.32.2->datasets) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\conda\lib\site-packages (from requests>=2.32.2->datasets) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in e:\conda\lib\site-packages (from requests>=2.32.2->datasets) (2024.6.2)
Requirement already satisfied: colorama in e:\conda\lib\site-packages (from tqdm>=4.66.3->datasets) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\conda\lib\site-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\conda\lib\site-packages (from pandas->datasets) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\conda\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: six>=1.5 in e:\conda\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)

In [4]:
#twitter emotion dataset in english
from datasets import load_dataset
twitter_english_dataset = load_dataset("dair-ai/emotion", "unsplit")

In [5]:
twitter_english_dataset

DatasetDict({
    train: Dataset({
        features: ['text', 'label'],
        num_rows: 416809
    })
})

In [6]:
#accessing the train and test set of twitter_english_dataset
import pandas as pd
df_twitter_train  = pd.DataFrame(twitter_english_dataset['train'])
df_twitter_train.head()

                                                text  label
0  i feel awful about it too because it s my job ...      0
1                              im alone i feel awful      0
2  ive probably mentioned this before but i reall...      1
3           i was feeling a little low few days back      0
4  i beleive that i am much more sensitive to oth...      2

In [7]:
label_names = twitter_english_dataset['train'].features['label'].names
label_names

['sadness', 'joy', 'love', 'anger', 'fear', 'surprise']

In [8]:
df_twitter_train['label'] = df_twitter_train['label'].apply(lambda x: label_names[x])
df_twitter_train.head()

                                                text    label
0  i feel awful about it too because it s my job ...  sadness
1                              im alone i feel awful  sadness
2  ive probably mentioned this before but i reall...      joy
3           i was feeling a little low few days back  sadness
4  i beleive that i am much more sensitive to oth...     love

In [9]:
df_twitter_train.isnull().any()

text     False
label    False
dtype: bool

In [10]:
print(df_twitter_train['label'].unique())
print(len(df_twitter_train))

['sadness' 'joy' 'love' 'anger' 'fear' 'surprise']
416809

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
df_twitter_train.head()

                                                text    label
0  i feel awful about it too because it s my job ...  sadness
1                              im alone i feel awful  sadness
2  ive probably mentioned this before but i reall...      joy
3           i was feeling a little low few days back  sadness
4  i beleive that i am much more sensitive to oth...     love

In [13]:
'''def twitter_train(df, test_size=0.2, val_size=0.1, random_state=42):
    # Step 1: Split into train and test sets
    df_tw_train, df_tw_test = train_test_split(df, test_size=test_size, random_state=random_state, stratify=df['label'])
    
    # Step 2: Split the training set into training and validation sets
    df__tw_train, df_tw_val = train_test_split(df_tw_train, test_size=val_size, random_state=random_state, stratify=df_tw_train['label'])
    
    return df_tw_train, df_tw_val, df_tw_test

# Split the dataset
df_tw_train, df_tw_val, df_tw_test = twitter_train(df_twitter_train)

# Display results
print("Training set size:", df_tw_train.shape[0])
print("Validation set size:", df_tw_val.shape[0])
print("Test set size:", df_tw_test.shape[0])

# Example of how to access the data
print("Sample training text:", df_tw_train['text'].iloc[0])
print("Sample training label:", df_tw_train['label'].iloc[0])'''

'def twitter_train(df, test_size=0.2, val_size=0.1, random_state=42):\n    # Step 1: Split into train and test sets\n    df_tw_train, df_tw_test = train_test_split(df, test_size=test_size, random_state=random_state, stratify=df[\'label\'])\n    \n    # Step 2: Split the training set into training and validation sets\n    df__tw_train, df_tw_val = train_test_split(df_tw_train, test_size=val_size, random_state=random_state, stratify=df_tw_train[\'label\'])\n    \n    return df_tw_train, df_tw_val, df_tw_test\n\n# Split the dataset\ndf_tw_train, df_tw_val, df_tw_test = twitter_train(df_twitter_train)\n\n# Display results\nprint("Training set size:", df_tw_train.shape[0])\nprint("Validation set size:", df_tw_val.shape[0])\nprint("Test set size:", df_tw_test.shape[0])\n\n# Example of how to access the data\nprint("Sample training text:", df_tw_train[\'text\'].iloc[0])\nprint("Sample training label:", df_tw_train[\'label\'].iloc[0])'

In [14]:
df_tw_train = df_twitter_train

In [15]:
df_tw_train.head()

                                                text    label
0  i feel awful about it too because it s my job ...  sadness
1                              im alone i feel awful  sadness
2  ive probably mentioned this before but i reall...      joy
3           i was feeling a little low few days back  sadness
4  i beleive that i am much more sensitive to oth...     love

In [16]:
#stopwords
!pip install nltk
!pip install indic-nlp-library
!pip install stopwords
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

Requirement already satisfied: nltk in e:\conda\lib\site-packages (3.8.1)
Requirement already satisfied: click in e:\conda\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in e:\conda\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in e:\conda\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in e:\conda\lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in e:\conda\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: indic-nlp-library in e:\conda\lib\site-packages (0.92)
Requirement already satisfied: sphinx-argparse in e:\conda\lib\site-packages (from indic-nlp-library) (0.5.2)
Requirement already satisfied: sphinx-rtd-theme in e:\conda\lib\site-packages (from indic-nlp-library) (2.0.0)
Requirement already satisfied: morfessor in e:\conda\lib\site-packages (from indic-nlp-library) (2.0.6)
Requirement already satisfied: pandas in e:\conda\lib\site-packages (from indic-nlp-library) (2.2.2)
Requirement already satisfied: numpy in e:\conda\lib\site-packages (from indic-nlp-library) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2023.3)
Requirement already satisfied: sphinx>=5.1.0 in e:\conda\lib\site-packages (from sphinx-argparse->indic-nlp-library) (7.3.7)
Requirement already satisfied: docutils>=0.19 in e:\conda\lib\site-packages (from sphinx-argparse->indic-nlp-library) (0.20.1)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in e:\conda\lib\site-packages (from sphinx-rtd-theme->indic-nlp-library) (4.1)
Requirement already satisfied: six>=1.5 in e:\conda\lib\site-packages (from python-dateutil>=2.8.2->pandas->indic-nlp-library) (1.16.0)
Requirement already satisfied: sphinxcontrib-applehelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.2)
Requirement already satisfied: sphinxcontrib-devhelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.2)
Requirement already satisfied: sphinxcontrib-jsmath in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.1.10)
Requirement already satisfied: sphinxcontrib-qthelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.3)
Requirement already satisfied: Jinja2>=3.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.4)
Requirement already satisfied: Pygments>=2.14 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.15.1)
Requirement already satisfied: snowballstemmer>=2.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.2.0)
Requirement already satisfied: babel>=2.9 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.11.0)
Requirement already satisfied: alabaster~=0.7.14 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (0.7.16)
Requirement already satisfied: imagesize>=1.3 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.4.1)
Requirement already satisfied: requests>=2.25.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.32.2)
Requirement already satisfied: packaging>=21.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (23.2)
Requirement already satisfied: colorama>=0.4.5 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in e:\conda\lib\site-packages (from Jinja2>=3.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2024.6.2)
Requirement already satisfied: stopwords in e:\conda\lib\site-packages (1.0.1)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [17]:
import re

# Function to clean text
def clean_text(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # Remove email addresses
    text = re.sub(r'\S*@\S*\s?', '', text)

    # Remove mentions (@usernames)
    text = re.sub(r'@\w+', '', text)

    # Remove hashtags
    text = re.sub(r'#\w+', '', text)

    # Remove special characters and numbers, keep only letters
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove extra whitespaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply the cleaning function to the DataFrame
df_tw_train['text'] = df_tw_train['text'].apply(clean_text)

# View the cleaned DataFrame
df_tw_train.head()

                                                text    label
0  i feel awful about it too because it s my job ...  sadness
1                              im alone i feel awful  sadness
2  ive probably mentioned this before but i reall...      joy
3           i was feeling a little low few days back  sadness
4  i beleive that i am much more sensitive to oth...     love

In [18]:
#Removoing stopwords
def remove_stopwords(text, language):
  stop_words = set(stopwords.words(language))
  word_tokens = word_tokenize(text)
  filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
  return " ".join(filtered_sentence)


df_tw_train['text'] = df_tw_train.apply(lambda row:
                               remove_stopwords(row['text'], 'english') if row['text'] is not None else '', axis=1)
df_tw_train.head()

                                                text    label
0         feel awful job get position succeed happen  sadness
1                                im alone feel awful  sadness
2  ive probably mentioned really feel proud actua...      joy
3                       feeling little low days back  sadness
4  beleive much sensitive peoples feelings tend c...     love

In [19]:
!pip install textblob
!python -m textblob.download_corpora

from textblob import Word
from textblob import TextBlob
import pandas as pd


# Function to lemmatize text using TextBlob
def lemmatize_text(text):
    # Break text into words, lemmatize each word, and join back into a sentence
    blob = TextBlob(text)
    return ' '.join([Word(word).lemmatize() for word in blob.words])

# Apply the lemmatization function to the 'text' column
df_tw_train['text'] = df_tw_train['text'].apply(lemmatize_text)

# Print the updated DataFrame
df_tw_train

Requirement already satisfied: textblob in e:\conda\lib\site-packages (0.18.0.post0)
Requirement already satisfied: nltk>=3.8 in e:\conda\lib\site-packages (from textblob) (3.8.1)
Requirement already satisfied: click in e:\conda\lib\site-packages (from nltk>=3.8->textblob) (8.1.7)
Requirement already satisfied: joblib in e:\conda\lib\site-packages (from nltk>=3.8->textblob) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in e:\conda\lib\site-packages (from nltk>=3.8->textblob) (2023.10.3)
Requirement already satisfied: tqdm in e:\conda\lib\site-packages (from nltk>=3.8->textblob) (4.66.4)
Requirement already satisfied: colorama in e:\conda\lib\site-packages (from click->nltk>=3.8->textblob) (0.4.6)
Finished.

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package conll2000 to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package conll2000 is already up-to-date!
[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package movie_reviews is already up-to-date!

                                                     text    label
0              feel awful job get position succeed happen  sadness
1                                     im alone feel awful  sadness
2       ive probably mentioned really feel proud actua...      joy
3                             feeling little low day back  sadness
4       beleive much sensitive people feeling tend com...     love
...                                                   ...      ...
416804  felt finally accepted bulgarian conservatorie ...      joy
416805  take every day come focussing eating better mo...     fear
416806                      suddenly feel everything fake  sadness
416807  im feeling eager ever claw back went pear shap...      joy
416808  give plenty attention even feel utterly miserable  sadness

[416809 rows x 2 columns]

In [20]:
df_tw_train.isnull().any()

text     False
label    False
dtype: bool

In [21]:
df_tw_train.iloc[1:10]

                                                text    label
1                                im alone feel awful  sadness
2  ive probably mentioned really feel proud actua...      joy
3                        feeling little low day back  sadness
4  beleive much sensitive people feeling tend com...     love
5  find frustrated christian feel constantly talk...     love
6     one people feel like going gym worthwhile hour      joy
7           feel especially pleased long time coming      joy
8  struggling awful feeling saying sweet thing de...      joy
9                         feel enraged helpless time    anger

In [22]:
df_tw_train_1 = pd.get_dummies(df_tw_train['label'])
df_tw_train_1.head()

   anger   fear    joy   love  sadness  surprise
0  False  False  False  False     True     False
1  False  False  False  False     True     False
2  False  False   True  False    False     False
3  False  False  False  False     True     False
4  False  False  False   True    False     False

In [23]:
df_tw_train_0 = df_tw_train.copy()
df_tw_train_0.drop(columns=['label'], inplace = True)
df_tw_train_main = pd.concat([df_tw_train_0, df_tw_train_1], axis=1)
df_tw_train_main.head()

,text,anger,fear,joy,love,sadness,surprise
0,feel awful job get position succeed happen,False,False,False,False,True,False
1,im alone feel awful,False,False,False,False,True,False
2,ive probably mentioned really feel proud actua...,False,False,True,False,False,False
3,feeling little low day back,False,False,False,False,True,False
4,beleive much sensitive people feeling tend com...,False,False,False,True,False,False

In [2]:
from datasets import load_dataset
twitter_english_dataset_2 = load_dataset("SemEvalWorkshop/sem_eval_2018_task_1", "subtask5.english")
twitter_english_dataset_2

DatasetDict({
    train: Dataset({
        features: ['ID', 'Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
        num_rows: 6838
    })
    test: Dataset({
        features: ['ID', 'Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
        num_rows: 3259
    })
    validation: Dataset({
        features: ['ID', 'Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
        num_rows: 886
    })
})

In [4]:
import pandas as pd
df_english_train = pd.DataFrame(twitter_english_dataset_2['train'])
df_english_train.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2017-En-21441,“Worry is a down payment on a problem you may ...,False,True,False,False,False,False,True,False,False,False,True
1,2017-En-31535,Whatever you decide to do make sure it makes y...,False,False,False,False,True,True,True,False,False,False,False
2,2017-En-21068,@Max_Kellerman it also helps that the majorit...,True,False,True,False,True,False,True,False,False,False,False
3,2017-En-31436,Accept the challenges so that you can literall...,False,False,False,False,True,False,True,False,False,False,False
4,2017-En-22195,My roommate: it's okay that we can't spell bec...,True,False,True,False,False,False,False,False,False,False,False

In [5]:
df_english_test = pd.DataFrame(twitter_english_dataset_2['test'])
df_english_test.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-En-01559,@Adnan__786__ @AsYouNotWish Dont worry Indian ...,True,True,False,False,False,False,True,False,False,False,True
1,2018-En-03739,"Academy of Sciences, eschews the normally sobe...",False,False,True,False,False,False,False,False,False,False,False
2,2018-En-00385,I blew that opportunity -__- #mad,True,False,True,False,False,False,False,False,True,False,False
3,2018-En-03001,This time in 2 weeks I will be 30... 😥,False,False,False,False,True,False,False,False,True,False,False
4,2018-En-01988,#Deppression is real. Partners w/ #depressed p...,False,False,False,True,False,False,False,False,True,False,False

In [6]:
df_english_validate = pd.DataFrame(twitter_english_dataset_2['validation'])
df_english_validate.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-En-00866,"@RanaAyyub @rajnathsingh Oh, hidden revenge an...",True,False,True,False,False,False,False,False,False,False,False
1,2018-En-02590,I'm doing all this to make sure you smiling do...,False,False,False,False,True,True,True,False,False,False,False
2,2018-En-03361,if not then #teamchristine bc all tana has don...,True,False,True,False,False,False,False,False,False,False,False
3,2018-En-03230,It is a #great start for #beginners to jump in...,False,False,False,False,True,False,True,False,False,False,False
4,2018-En-01143,My best friends driving for the first time wit...,False,False,False,True,False,False,False,False,False,False,False

In [7]:
df_english_comb = pd.concat([df_english_train, df_english_test, df_english_validate])
df_english_comb.size

142779

In [8]:
df_english_comb.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2017-En-21441,“Worry is a down payment on a problem you may ...,False,True,False,False,False,False,True,False,False,False,True
1,2017-En-31535,Whatever you decide to do make sure it makes y...,False,False,False,False,True,True,True,False,False,False,False
2,2017-En-21068,@Max_Kellerman it also helps that the majorit...,True,False,True,False,True,False,True,False,False,False,False
3,2017-En-31436,Accept the challenges so that you can literall...,False,False,False,False,True,False,True,False,False,False,False
4,2017-En-22195,My roommate: it's okay that we can't spell bec...,True,False,True,False,False,False,False,False,False,False,False

In [9]:
df_eng_comb = df_english_comb.drop(columns=['ID'])
df_eng_comb.head()
df_eng_comb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10983 entries, 0 to 885
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tweet         10983 non-null  object
 1   anger         10983 non-null  bool
 2   anticipation  10983 non-null  bool
 3   disgust       10983 non-null  bool
 4   fear          10983 non-null  bool
 5   joy           10983 non-null  bool
 6   love          10983 non-null  bool
 7   optimism      10983 non-null  bool
 8   pessimism     10983 non-null  bool
 9   sadness       10983 non-null  bool
 10  surprise      10983 non-null  bool
 11  trust         10983 non-null  bool
dtypes: bool(11), object(1)
memory usage: 289.6+ KB

In [10]:
'''from sklearn.model_selection import train_test_split
def english_comb(df, test_size=0.2, val_size=0.1, random_state=42):
    # Step 1: Split into train and test sets
    df_eng_train, df_eng_test = train_test_split(df, test_size=test_size, random_state=random_state)
    
    # Step 2: Split the training set into training and validation sets
    df__eng_train, df_eng_val = train_test_split(df_eng_train, test_size=val_size, random_state=random_state)
    
    return df_eng_train, df_eng_val, df_eng_test

# Split the dataset
df_eng_train, df_eng_val, df_eng_test = english_comb(df_eng_comb)

# Display results
print("Training set size:", df_eng_train.shape[0])
print("Validation set size:", df_eng_val.shape[0])
print("Test set size:", df_eng_test.shape[0])

# Example of how to access the data
print("Sample training text:", df_eng_train['Tweet'].iloc[0])
print("Sample training label:", df_eng_train['Tweet'].iloc[0])'''

'from sklearn.model_selection import train_test_split\ndef english_comb(df, test_size=0.2, val_size=0.1, random_state=42):\n    # Step 1: Split into train and test sets\n    df_eng_train, df_eng_test = train_test_split(df, test_size=test_size, random_state=random_state)\n    \n    # Step 2: Split the training set into training and validation sets\n    df__eng_train, df_eng_val = train_test_split(df_eng_train, test_size=val_size, random_state=random_state)\n    \n    return df_eng_train, df_eng_val, df_eng_test\n\n# Split the dataset\ndf_eng_train, df_eng_val, df_eng_test = english_comb(df_eng_comb)\n\n# Display results\nprint("Training set size:", df_eng_train.shape[0])\nprint("Validation set size:", df_eng_val.shape[0])\nprint("Test set size:", df_eng_test.shape[0])\n\n# Example of how to access the data\nprint("Sample training text:", df_eng_train[\'Tweet\'].iloc[0])\nprint("Sample training label:", df_eng_train[\'Tweet\'].iloc[0])'

In [11]:
df_eng_train = df_eng_comb

In [12]:
df_eng_train.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,“Worry is a down payment on a problem you may ...,False,True,False,False,False,False,True,False,False,False,True
1,Whatever you decide to do make sure it makes y...,False,False,False,False,True,True,True,False,False,False,False
2,@Max_Kellerman it also helps that the majorit...,True,False,True,False,True,False,True,False,False,False,False
3,Accept the challenges so that you can literall...,False,False,False,False,True,False,True,False,False,False,False
4,My roommate: it's okay that we can't spell bec...,True,False,True,False,False,False,False,False,False,False,False

In [13]:
#stopwords
!pip install nltk
!pip install indic-nlp-library
!pip install stopwords
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

Requirement already satisfied: nltk in e:\conda\lib\site-packages (3.8.1)
Requirement already satisfied: click in e:\conda\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in e:\conda\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in e:\conda\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in e:\conda\lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in e:\conda\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: indic-nlp-library in e:\conda\lib\site-packages (0.92)
Requirement already satisfied: sphinx-argparse in e:\conda\lib\site-packages (from indic-nlp-library) (0.5.2)
Requirement already satisfied: sphinx-rtd-theme in e:\conda\lib\site-packages (from indic-nlp-library) (2.0.0)
Requirement already satisfied: morfessor in e:\conda\lib\site-packages (from indic-nlp-library) (2.0.6)
Requirement already satisfied: pandas in e:\conda\lib\site-packages (from indic-nlp-library) (2.2.2)
Requirement already satisfied: numpy in e:\conda\lib\site-packages (from indic-nlp-library) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2023.3)
Requirement already satisfied: sphinx>=5.1.0 in e:\conda\lib\site-packages (from sphinx-argparse->indic-nlp-library) (7.3.7)
Requirement already satisfied: docutils>=0.19 in e:\conda\lib\site-packages (from sphinx-argparse->indic-nlp-library) (0.20.1)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in e:\conda\lib\site-packages (from sphinx-rtd-theme->indic-nlp-library) (4.1)
Requirement already satisfied: six>=1.5 in e:\conda\lib\site-packages (from python-dateutil>=2.8.2->pandas->indic-nlp-library) (1.16.0)
Requirement already satisfied: sphinxcontrib-applehelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.2)
Requirement already satisfied: sphinxcontrib-devhelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.2)
Requirement already satisfied: sphinxcontrib-jsmath in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.1.10)
Requirement already satisfied: sphinxcontrib-qthelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.3)
Requirement already satisfied: Jinja2>=3.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.4)
Requirement already satisfied: Pygments>=2.14 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.15.1)
Requirement already satisfied: snowballstemmer>=2.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.2.0)
Requirement already satisfied: babel>=2.9 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.11.0)
Requirement already satisfied: alabaster~=0.7.14 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (0.7.16)
Requirement already satisfied: imagesize>=1.3 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.4.1)
Requirement already satisfied: requests>=2.25.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.32.2)
Requirement already satisfied: packaging>=21.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (23.2)
Requirement already satisfied: colorama>=0.4.5 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in e:\conda\lib\site-packages (from Jinja2>=3.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2024.6.2)
Requirement already satisfied: stopwords in e:\conda\lib\site-packages (1.0.1)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [14]:
import re

# Function to clean text
def clean_text(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # Remove email addresses
    text = re.sub(r'\S*@\S*\s?', '', text)

    # Remove mentions (@usernames)
    text = re.sub(r'@\w+', '', text)

    # Remove hashtags
    text = re.sub(r'#\w+', '', text)

    # Remove special characters and numbers, keep only letters
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove extra whitespaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply the cleaning function to the DataFrame
df_eng_train['Tweet'] = df_eng_train['Tweet'].apply(clean_text)

# View the cleaned DataFrame
df_eng_train.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,worry is a down payment on a problem you may n...,False,True,False,False,False,False,True,False,False,False,True
1,whatever you decide to do make sure it makes you,False,False,False,False,True,True,True,False,False,False,False
2,it also helps that the majority of nfl coachin...,True,False,True,False,True,False,True,False,False,False,False
3,accept the challenges so that you can literall...,False,False,False,False,True,False,True,False,False,False,False
4,my roommate its okay that we cant spell becaus...,True,False,True,False,False,False,False,False,False,False,False

In [15]:
#Removoing stopwords
def remove_stopwords(text, language):
  stop_words = set(stopwords.words(language))
  word_tokens = word_tokenize(text)
  filtered_sentence = [w for w in word_tokens if not w.lower() in stop_words]
  return " ".join(filtered_sentence)


df_eng_train['Tweet'] = df_eng_train.apply(lambda row:
                               remove_stopwords(row['Tweet'], 'english') if row['Tweet'] is not None else '', axis=1)
df_eng_train.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,worry payment problem may never joyce meyer,False,True,False,False,False,False,True,False,False,False,True
1,whatever decide make sure makes,False,False,False,False,True,True,True,False,False,False,False
2,also helps majority nfl coaching inept bill ob...,True,False,True,False,True,False,True,False,False,False,False
3,accept challenges literally even feel exhilara...,False,False,False,False,True,False,True,False,False,False,False
4,roommate okay cant spell autocorrect,True,False,True,False,False,False,False,False,False,False,False

In [16]:
!pip install stanza
import stanza

# Download Hindi language model
stanza.download('en')

Requirement already satisfied: stanza in e:\conda\lib\site-packages (1.9.2)
Requirement already satisfied: emoji in e:\conda\lib\site-packages (from stanza) (2.13.2)
Requirement already satisfied: numpy in e:\conda\lib\site-packages (from stanza) (1.26.4)
Requirement already satisfied: protobuf>=3.15.0 in e:\conda\lib\site-packages (from stanza) (3.20.3)
Requirement already satisfied: requests in e:\conda\lib\site-packages (from stanza) (2.32.2)
Requirement already satisfied: networkx in e:\conda\lib\site-packages (from stanza) (3.2.1)
Requirement already satisfied: torch>=1.3.0 in e:\conda\lib\site-packages (from stanza) (2.4.1)
Requirement already satisfied: tqdm in e:\conda\lib\site-packages (from stanza) (4.66.4)
Requirement already satisfied: filelock in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (4.11.0)
Requirement already satisfied: sympy in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (1.12)
Requirement already satisfied: jinja2 in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (3.1.4)
Requirement already satisfied: fsspec in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (2024.3.1)
Requirement already satisfied: setuptools in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (69.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\conda\lib\site-packages (from requests->stanza) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in e:\conda\lib\site-packages (from requests->stanza) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\conda\lib\site-packages (from requests->stanza) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in e:\conda\lib\site-packages (from requests->stanza) (2024.6.2)
Requirement already satisfied: colorama in e:\conda\lib\site-packages (from tqdm->stanza) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in e:\conda\lib\site-packages (from jinja2->torch>=1.3.0->stanza) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in e:\conda\lib\site-packages (from sympy->torch>=1.3.0->stanza) (1.3.0)

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json:   0%|   …

2024-10-24 16:18:26 INFO: Downloaded file to C:\Users\Harsha\stanza_resources\resources.json
2024-10-24 16:18:26 INFO: Downloading default packages for language: en (English) ...
2024-10-24 16:18:27 INFO: File exists: C:\Users\Harsha\stanza_resources\en\default.zip
2024-10-24 16:18:30 INFO: Finished downloading models and saved to C:\Users\Harsha\stanza_resources

In [17]:
import pandas as pd
import stanza

# Initialize the Hindi NLP pipeline
stanza.download('en')  # Download the Hindi model
nlp = stanza.Pipeline('en')

# Example DataFrame

def lemmatize_hindi(text):
    # Process the text with Stanza
    doc = nlp(text)
    # Get lemmas for each token
    lemmas = [word.lemma for sent in doc.sentences for word in sent.words]
    # Join the lemmas back into a string
    return ' '.join(lemmas)

# Apply the lemmatization function to the 'Tweet' column
df_eng_train['Tweet'] = df_eng_train['Tweet'].apply(lemmatize_hindi)

# Display the DataFrame with the lemmatized tweets
df_eng_train

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json:   0%|   …

2024-10-24 16:18:30 INFO: Downloaded file to C:\Users\Harsha\stanza_resources\resources.json
2024-10-24 16:18:30 INFO: Downloading default packages for language: en (English) ...
2024-10-24 16:18:31 INFO: File exists: C:\Users\Harsha\stanza_resources\en\default.zip
2024-10-24 16:18:33 INFO: Finished downloading models and saved to C:\Users\Harsha\stanza_resources
2024-10-24 16:18:33 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json:   0%|   …

2024-10-24 16:18:33 INFO: Downloaded file to C:\Users\Harsha\stanza_resources\resources.json
2024-10-24 16:18:35 INFO: Loading these models for language: en (English):
============================================
| Processor    | Package                   |
--------------------------------------------
| tokenize     | combined                  |
| mwt          | combined                  |
| pos          | combined_charlm           |
| lemma        | combined_nocharlm         |
| constituency | ptb3-revised_charlm       |
| depparse     | combined_charlm           |
| sentiment    | sstplus_charlm            |
| ner          | ontonotes-ww-multi_charlm |
============================================

2024-10-24 16:18:35 INFO: Using device: cpu
2024-10-24 16:18:35 INFO: Loading: tokenize
E:\conda\Lib\site-packages\stanza\models\tokenization\trainer.py:82: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 16:18:35 INFO: Loading: mwt
E:\conda\Lib\site-packages\stanza\models\mwt\trainer.py:201: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 16:18:35 INFO: Loading: pos
E:\conda\Lib\site-packages\stanza\models\pos\trainer.py:139: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
E:\conda\Lib\site-packages\stanza\models\common\pretrain.py:56: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(self.filename, lambda storage, loc: storage)
E:\conda\Lib\site-packages\stanza\models\common\char_model.py:271: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(filename, lambda storage, loc: storage)
2024-10-24 16:18:36 INFO: Loading: lemma
E:\conda\Lib\site-packages\stanza\models\lemma\trainer.py:239: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 16:18:36 INFO: Loading: constituency
E:\conda\Lib\site-packages\stanza\models\constituency\base_trainer.py:87: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 16:18:36 INFO: Loading: depparse
E:\conda\Lib\site-packages\stanza\models\depparse\trainer.py:194: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 16:18:37 INFO: Loading: sentiment
E:\conda\Lib\site-packages\stanza\models\classifiers\trainer.py:72: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 16:18:37 INFO: Loading: ner
E:\conda\Lib\site-packages\stanza\models\ner\trainer.py:197: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 16:18:37 INFO: Done loading processors!

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,worry payment problem may never joyce meyer,False,True,False,False,False,False,True,False,False,False,True
1,whatever decide make sure make,False,False,False,False,True,True,True,False,False,False,False
2,also help majority nfl coaching inept bill obr...,True,False,True,False,True,False,True,False,False,False,False
3,accept challenge literally even feel exhilarat...,False,False,False,False,True,False,True,False,False,False,False
4,roommate okay cant spell autocorrect,True,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
881,do not make angry id laugh tweet,True,False,True,False,False,False,False,False,False,False,False
882,excited watch tonight come NSw,False,False,False,False,True,False,True,False,False,False,False
883,blah blah blah kyrie etc. leave boston real news,True,False,True,False,False,False,False,False,True,False,False
884,wise never trust flock wolf,False,False,False,False,False,False,False,False,False,False,False
885,really flatter happy hear complement blog guy ...,False,False,False,False,True,False,True,False,False,False,False

In [18]:
df_eng_train

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,worry payment problem may never joyce meyer,False,True,False,False,False,False,True,False,False,False,True
1,whatever decide make sure make,False,False,False,False,True,True,True,False,False,False,False
2,also help majority nfl coaching inept bill obr...,True,False,True,False,True,False,True,False,False,False,False
3,accept challenge literally even feel exhilarat...,False,False,False,False,True,False,True,False,False,False,False
4,roommate okay cant spell autocorrect,True,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
881,do not make angry id laugh tweet,True,False,True,False,False,False,False,False,False,False,False
882,excited watch tonight come NSw,False,False,False,False,True,False,True,False,False,False,False
883,blah blah blah kyrie etc. leave boston real news,True,False,True,False,False,False,False,False,True,False,False
884,wise never trust flock wolf,False,False,False,False,False,False,False,False,False,False,False
885,really flatter happy hear complement blog guy ...,False,False,False,False,True,False,True,False,False,False,False

In [19]:
df_eng_train.isnull().any()

Tweet           False
anger           False
anticipation    False
disgust         False
fear            False
joy             False
love            False
optimism        False
pessimism       False
sadness         False
surprise        False
trust           False
dtype: bool

In [41]:
from datasets import load_dataset
spanish_twitter_dataset = load_dataset("SemEvalWorkshop/sem_eval_2018_task_1", "subtask5.spanish")
spanish_twitter_dataset

DatasetDict({
    train: Dataset({
        features: ['ID', 'Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
        num_rows: 3561
    })
    test: Dataset({
        features: ['ID', 'Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
        num_rows: 2854
    })
    validation: Dataset({
        features: ['ID', 'Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
        num_rows: 679
    })
})

In [42]:
import pandas as pd
df_spanish_train = pd.DataFrame(spanish_twitter_dataset['train'])
df_spanish_train.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-01643,@aliciaenp Ajajjaa somos del clan twitteras pe...,False,False,False,False,True,False,False,False,False,False,False
1,2018-Es-05142,@AwadaNai la mala suerte del gato fichame la c...,False,False,False,True,False,False,False,True,False,False,False
2,2018-Es-05379,@audiomano A mí tampoco me agrado mucho eso. E...,True,False,False,False,False,False,False,False,False,False,False
3,2018-Es-00208,Para llevar a los bebes de un lugar a otro deb...,False,False,False,False,True,False,False,False,False,False,False
4,2018-Es-01385,@DalasReview me encanta la terrible hipocresia...,True,False,True,False,False,False,False,False,False,False,False

In [43]:
import pandas as pd
df_spanish_test = pd.DataFrame(spanish_twitter_dataset['test'])
df_spanish_test.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-07180,@Reforma QEPD 😢 Mis condolencias para sus fami...,False,False,False,False,False,False,False,False,True,False,False
1,2018-Es-00392,@Mubrutico @AlvaroVadin @aracnoideo Estoy enfa...,True,False,False,False,False,False,False,False,False,False,False
2,2018-Es-06102,@jotajordi13 @somhiserem @jmbartomeu Que estas...,True,False,False,False,False,False,False,False,False,False,False
3,2018-Es-05390,"""Tienes esa sonrisa que me gustaría ver cada d...",False,False,False,False,True,True,False,False,False,False,False
4,2018-Es-00153,Q horrible es querer dormir y no poder dormir ...,True,False,False,False,False,False,False,True,True,False,False

In [44]:
import pandas as pd
df_spanish_validate = pd.DataFrame(spanish_twitter_dataset['validation'])
df_spanish_validate.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-06697,No me pienso perder la pelea de McGregor contr...,False,True,False,False,False,False,False,False,False,False,False
1,2018-Es-05385,Yo preocupada pensando que mi papá ya había ll...,False,True,False,True,False,False,False,False,False,False,False
2,2018-Es-03777,Pucha ya no me sirven todos los carros a Rondi...,False,False,False,False,True,False,False,False,False,False,False
3,2018-Es-02175,"Si estar contigo es un delito, hago cien años ...",False,False,False,False,True,True,False,False,False,False,False
4,2018-Es-00726,@macacifuentesC @sergmujica Perfect... Y de un...,False,False,True,False,False,False,False,False,False,False,False

In [45]:
#combining spanish dataset (train , test and validation)
df_spanish_combined = pd.concat([df_spanish_train, df_spanish_test, df_spanish_validate])

In [46]:
df_spanish_combined.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-01643,@aliciaenp Ajajjaa somos del clan twitteras pe...,False,False,False,False,True,False,False,False,False,False,False
1,2018-Es-05142,@AwadaNai la mala suerte del gato fichame la c...,False,False,False,True,False,False,False,True,False,False,False
2,2018-Es-05379,@audiomano A mí tampoco me agrado mucho eso. E...,True,False,False,False,False,False,False,False,False,False,False
3,2018-Es-00208,Para llevar a los bebes de un lugar a otro deb...,False,False,False,False,True,False,False,False,False,False,False
4,2018-Es-01385,@DalasReview me encanta la terrible hipocresia...,True,False,True,False,False,False,False,False,False,False,False

In [47]:
len(df_spanish_combined)

7094

In [48]:
df_spa_comb = df_spanish_combined.drop(columns=['ID'])
df_spa_comb.head()
df_spa_comb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7094 entries, 0 to 678
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tweet         7094 non-null   object
 1   anger         7094 non-null   bool
 2   anticipation  7094 non-null   bool
 3   disgust       7094 non-null   bool
 4   fear          7094 non-null   bool
 5   joy           7094 non-null   bool
 6   love          7094 non-null   bool
 7   optimism      7094 non-null   bool
 8   pessimism     7094 non-null   bool
 9   sadness       7094 non-null   bool
 10  surprise      7094 non-null   bool
 11  trust         7094 non-null   bool
dtypes: bool(11), object(1)
memory usage: 187.0+ KB

In [49]:
df_spa_comb.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,@aliciaenp Ajajjaa somos del clan twitteras pe...,False,False,False,False,True,False,False,False,False,False,False
1,@AwadaNai la mala suerte del gato fichame la c...,False,False,False,True,False,False,False,True,False,False,False
2,@audiomano A mí tampoco me agrado mucho eso. E...,True,False,False,False,False,False,False,False,False,False,False
3,Para llevar a los bebes de un lugar a otro deb...,False,False,False,False,True,False,False,False,False,False,False
4,@DalasReview me encanta la terrible hipocresia...,True,False,True,False,False,False,False,False,False,False,False

In [50]:
'''from sklearn.model_selection import train_test_split
def spanish_comb(df, test_size=0.2, val_size=0.1, random_state=42):
    # Step 1: Split into train and test sets
    df_spa_train, df_spa_test = train_test_split(df, test_size=test_size, random_state=random_state)
    
    # Step 2: Split the training set into training and validation sets
    df__spa_train, df_spa_val = train_test_split(df_spa_train, test_size=val_size, random_state=random_state)
    
    return df_spa_train, df_spa_val, df_spa_test

# Split the dataset
df_spa_train, df_spa_val, df_spa_test = spanish_comb(df_spa_comb)

# Display results
print("Training set size:", df_spa_train.shape[0])
print("Validation set size:", df_spa_val.shape[0])
print("Test set size:", df_spa_test.shape[0])

# Example of how to access the data
print("Sample training text:", df_spa_train['Tweet'].iloc[0])
print("Sample training label:", df_spa_train['Tweet'].iloc[0])'''

'from sklearn.model_selection import train_test_split\ndef spanish_comb(df, test_size=0.2, val_size=0.1, random_state=42):\n    # Step 1: Split into train and test sets\n    df_spa_train, df_spa_test = train_test_split(df, test_size=test_size, random_state=random_state)\n    \n    # Step 2: Split the training set into training and validation sets\n    df__spa_train, df_spa_val = train_test_split(df_spa_train, test_size=val_size, random_state=random_state)\n    \n    return df_spa_train, df_spa_val, df_spa_test\n\n# Split the dataset\ndf_spa_train, df_spa_val, df_spa_test = spanish_comb(df_spa_comb)\n\n# Display results\nprint("Training set size:", df_spa_train.shape[0])\nprint("Validation set size:", df_spa_val.shape[0])\nprint("Test set size:", df_spa_test.shape[0])\n\n# Example of how to access the data\nprint("Sample training text:", df_spa_train[\'Tweet\'].iloc[0])\nprint("Sample training label:", df_spa_train[\'Tweet\'].iloc[0])'

In [51]:
df_spa_train = df_spa_comb

In [52]:
df_spa_train.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,@aliciaenp Ajajjaa somos del clan twitteras pe...,False,False,False,False,True,False,False,False,False,False,False
1,@AwadaNai la mala suerte del gato fichame la c...,False,False,False,True,False,False,False,True,False,False,False
2,@audiomano A mí tampoco me agrado mucho eso. E...,True,False,False,False,False,False,False,False,False,False,False
3,Para llevar a los bebes de un lugar a otro deb...,False,False,False,False,True,False,False,False,False,False,False
4,@DalasReview me encanta la terrible hipocresia...,True,False,True,False,False,False,False,False,False,False,False

In [53]:
import re

# Function to clean text
def clean_text(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # Remove email addresses
    text = re.sub(r'\S*@\S*\s?', '', text)

    # Remove mentions (@usernames)
    text = re.sub(r'@\w+', '', text)

    # Remove hashtags
    text = re.sub(r'#\w+', '', text)

    # Remove special characters and numbers, keep only letters
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove extra whitespaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply the cleaning function to the DataFrame
df_spa_train['Tweet'] = df_spa_train['Tweet'].apply(clean_text)

# View the cleaned DataFrame
df_spa_train.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,ajajjaa somos del clan twitteras perdidas pa e...,False,False,False,False,True,False,False,False,False,False,False
1,la mala suerte del gato fichame la cara de hel...,False,False,False,True,False,False,False,True,False,False,False
2,a m tampoco me agrado mucho eso especialmente ...,True,False,False,False,False,False,False,False,False,False,False
3,para llevar a los bebes de un lugar a otro deb...,False,False,False,False,True,False,False,False,False,False,False
4,me encanta la terrible hipocresia y doble mora...,True,False,True,False,False,False,False,False,False,False,False

In [54]:
#stopwords
!pip install nltk
!pip install indic-nlp-library
!pip install stopwords
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

Requirement already satisfied: nltk in e:\conda\lib\site-packages (3.8.1)
Requirement already satisfied: click in e:\conda\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in e:\conda\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in e:\conda\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in e:\conda\lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in e:\conda\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: indic-nlp-library in e:\conda\lib\site-packages (0.92)
Requirement already satisfied: sphinx-argparse in e:\conda\lib\site-packages (from indic-nlp-library) (0.5.2)
Requirement already satisfied: sphinx-rtd-theme in e:\conda\lib\site-packages (from indic-nlp-library) (2.0.0)
Requirement already satisfied: morfessor in e:\conda\lib\site-packages (from indic-nlp-library) (2.0.6)
Requirement already satisfied: pandas in e:\conda\lib\site-packages (from indic-nlp-library) (2.2.2)
Requirement already satisfied: numpy in e:\conda\lib\site-packages (from indic-nlp-library) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2023.3)
Requirement already satisfied: sphinx>=5.1.0 in e:\conda\lib\site-packages (from sphinx-argparse->indic-nlp-library) (7.3.7)
Requirement already satisfied: docutils>=0.19 in e:\conda\lib\site-packages (from sphinx-argparse->indic-nlp-library) (0.20.1)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in e:\conda\lib\site-packages (from sphinx-rtd-theme->indic-nlp-library) (4.1)
Requirement already satisfied: six>=1.5 in e:\conda\lib\site-packages (from python-dateutil>=2.8.2->pandas->indic-nlp-library) (1.16.0)
Requirement already satisfied: sphinxcontrib-applehelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.2)
Requirement already satisfied: sphinxcontrib-devhelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.2)
Requirement already satisfied: sphinxcontrib-jsmath in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.1.10)
Requirement already satisfied: sphinxcontrib-qthelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.3)
Requirement already satisfied: Jinja2>=3.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.4)
Requirement already satisfied: Pygments>=2.14 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.15.1)
Requirement already satisfied: snowballstemmer>=2.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.2.0)
Requirement already satisfied: babel>=2.9 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.11.0)
Requirement already satisfied: alabaster~=0.7.14 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (0.7.16)
Requirement already satisfied: imagesize>=1.3 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.4.1)
Requirement already satisfied: requests>=2.25.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.32.2)
Requirement already satisfied: packaging>=21.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (23.2)
Requirement already satisfied: colorama>=0.4.5 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in e:\conda\lib\site-packages (from Jinja2>=3.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2024.6.2)
Requirement already satisfied: stopwords in e:\conda\lib\site-packages (1.0.1)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [55]:
#removing stop words from text
import nltk
from nltk.corpus import stopwords
import re

nltk.download('stopwords')
spanish_stopwords = set(stopwords.words('spanish'))

def remove_stopwords(text):
  #tokenizing
  words = re.findall(r'\b\w+\b', text.lower())

  filtered_words = [word for word in words if word not in spanish_stopwords]

  return ' '.join(filtered_words)

df_spa_train['Tweet'] = df_spa_train['Tweet'].apply(remove_stopwords)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [56]:
df_spa_train.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,ajajjaa clan twitteras perdidas pa eventos imp...,False,False,False,False,True,False,False,False,False,False,False
1,mala suerte gato fichame cara help pls,False,False,False,True,False,False,False,True,False,False,False
2,m tampoco agrado especialmente tratarse l just...,True,False,False,False,False,False,False,False,False,False,False
3,llevar bebes lugar debemos cantarles canciones...,False,False,False,False,True,False,False,False,False,False,False
4,encanta terrible hipocresia doble moral gente ...,True,False,True,False,False,False,False,False,False,False,False

In [57]:
import stanza
import pandas as pd

In [58]:

# Initialize the Spanish NLP pipeline
stanza.download('es')
nlp = stanza.Pipeline('es', processors='tokenize,mwt,pos,lemma')


# Function to lemmatize text using Stanza
def lemmatize_sentence(sentence):
    doc = nlp(sentence)
    return " ".join([word.lemma for sent in doc.sentences for word in sent.words])

# Apply the lemmatization to the DataFrame column
df_spa_train['Tweet'] = df_spa_train['Tweet'].apply(lemmatize_sentence)

# Display the DataFrame with lemmatized text
df_spa_train

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json:   0%|   …

2024-10-24 14:33:47 INFO: Downloaded file to C:\Users\Harsha\stanza_resources\resources.json
2024-10-24 14:33:47 INFO: Downloading default packages for language: es (Spanish) ...
2024-10-24 14:33:49 INFO: File exists: C:\Users\Harsha\stanza_resources\es\default.zip
2024-10-24 14:33:54 INFO: Finished downloading models and saved to C:\Users\Harsha\stanza_resources
2024-10-24 14:33:54 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json:   0%|   …

2024-10-24 14:33:54 INFO: Downloaded file to C:\Users\Harsha\stanza_resources\resources.json
2024-10-24 14:33:55 INFO: Loading these models for language: es (Spanish):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| pos       | combined_charlm   |
| lemma     | combined_nocharlm |
=================================

2024-10-24 14:33:55 INFO: Using device: cpu
2024-10-24 14:33:55 INFO: Loading: tokenize
E:\conda\Lib\site-packages\stanza\models\tokenization\trainer.py:82: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 14:33:55 INFO: Loading: mwt
E:\conda\Lib\site-packages\stanza\models\mwt\trainer.py:201: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 14:33:55 INFO: Loading: pos
E:\conda\Lib\site-packages\stanza\models\pos\trainer.py:139: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
E:\conda\Lib\site-packages\stanza\models\common\pretrain.py:56: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(self.filename, lambda storage, loc: storage)
E:\conda\Lib\site-packages\stanza\models\common\char_model.py:271: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(filename, lambda storage, loc: storage)
2024-10-24 14:33:55 INFO: Loading: lemma
E:\conda\Lib\site-packages\stanza\models\lemma\trainer.py:239: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 14:33:55 INFO: Done loading processors!

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,ajajjaa clan twittera perdido pa evento import...,False,False,False,False,True,False,False,False,False,False,False
1,malo suerte gato fichame cara help pls,False,False,False,True,False,False,False,True,False,False,False
2,m tampoco agrado especialmente tratar él l jus...,True,False,False,False,False,False,False,False,False,False,False
3,llevar bebe lugar deber cantar él canción quer...,False,False,False,False,True,False,False,False,False,False,False
4,encantar terrible hipocresia doble moral gente...,True,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
674,peligro volante tec santo memes galleta c,False,False,False,True,False,False,False,False,False,False,False
675,ir ver q sucedio barrio,False,True,False,False,False,False,False,False,False,False,False
676,felicidad fer pasar agus dar él like foto caro...,False,False,False,False,True,False,False,False,False,False,False
677,lamento confusin rama legislativo contar publi...,False,False,False,False,False,False,False,False,False,False,False
678,sobrina ver foto pared tú decir mirar ta ah co...,False,False,False,False,True,False,False,False,False,False,False

In [59]:
df_spa_train.isnull().any()

Tweet           False
anger           False
anticipation    False
disgust         False
fear            False
joy             False
love            False
optimism        False
pessimism       False
sadness         False
surprise        False
trust           False
dtype: bool

In [60]:
import pandas as pd
#Loading the hindi dataset
file_path  = 'C:\\Users\\Harsha\\Downloads\\hin\\output_combined_data_processed (1).csv'
df_hindi = pd.read_csv(file_path)
df_hindi["Label"].unique()
print(len(df_hindi))

8000

In [61]:
df_hindi.head()

      Label                                           Sentence
0   neutral                             आप अपने हाथ भरे होंगे।
1   neutral                      कि मैंने किया। कि मैंने किया।
2   neutral  तो चलो अपने कर्तव्यों के बारे में थोड़ा बात करें।
3  surprise                              मेरे कर्तव्य? ठीक है.
4   neutral  अब आप एक पूरे डिवीजन का नेतृत्व करेंगे, तो आप ...

In [62]:
'''from sklearn.model_selection import train_test_split
def hindi(df, test_size=0.2, val_size=0.1, random_state=42):
    # Step 1: Split into train and test sets
    df_hin_train, df_hin_test = train_test_split(df, test_size=test_size, random_state=random_state, stratify=df['Label'])
    
    # Step 2: Split the training set into training and validation sets
    df__hin_train, df_hin_val = train_test_split(df_hin_train, test_size=val_size, random_state=random_state, stratify=df_hin_train['Label'])
    
    return df_hin_train, df_hin_val, df_hin_test

# Split the dataset
df_hin_train, df_hin_val, df_hin_test = hindi(df_hindi)

# Display results
print("Training set size:", df_hin_train.shape[0])
print("Validation set size:", df_hin_val.shape[0])
print("Test set size:", df_hin_test.shape[0])

# Example of how to access the data
print("Sample training text:", df_hin_train['Sentence'].iloc[0])
print("Sample training label:", df_hin_train['Label'].iloc[0])'''

'from sklearn.model_selection import train_test_split\ndef hindi(df, test_size=0.2, val_size=0.1, random_state=42):\n    # Step 1: Split into train and test sets\n    df_hin_train, df_hin_test = train_test_split(df, test_size=test_size, random_state=random_state, stratify=df[\'Label\'])\n    \n    # Step 2: Split the training set into training and validation sets\n    df__hin_train, df_hin_val = train_test_split(df_hin_train, test_size=val_size, random_state=random_state, stratify=df_hin_train[\'Label\'])\n    \n    return df_hin_train, df_hin_val, df_hin_test\n\n# Split the dataset\ndf_hin_train, df_hin_val, df_hin_test = hindi(df_hindi)\n\n# Display results\nprint("Training set size:", df_hin_train.shape[0])\nprint("Validation set size:", df_hin_val.shape[0])\nprint("Test set size:", df_hin_test.shape[0])\n\n# Example of how to access the data\nprint("Sample training text:", df_hin_train[\'Sentence\'].iloc[0])\nprint("Sample training label:", df_hin_train[\'Label\'].iloc[0])'

In [63]:
df_hin_train = df_hindi

In [64]:
df_hi_train = df_hin_train.copy

In [65]:
df_hi_train

<bound method NDFrame.copy of          Label                                           Sentence
0      neutral                             आप अपने हाथ भरे होंगे।
1      neutral                      कि मैंने किया। कि मैंने किया।
2      neutral  तो चलो अपने कर्तव्यों के बारे में थोड़ा बात करें।
3     surprise                              मेरे कर्तव्य? ठीक है.
4      neutral  अब आप एक पूरे डिवीजन का नेतृत्व करेंगे, तो आप ...
...        ...                                                ...
7995       joy  अधिक लंदन? नहीं-नहीं, रोम? विनय? ओह-ओह, बार्सि...
7996     anger  ठीक है, क्या आप बस एक सेकंड के लिए बात बंद कर ...
7997     anger                                                कब?
7998   neutral                                मैं ठीक नहीं जानता।
7999   sadness  ओह, अच्छी तरह से मैं उस क्षण आने तक चंडलर बिंं...

[8000 rows x 2 columns]>

In [66]:
import pandas as pd
import re

def clean_hindi_text(text):
   # Remove everything that is not a Hindi character or space, including full stop "।"
    text = re.sub(r'[^\u0900-\u097F\s]', '', text)

    # Remove Hindi full stop '।' explicitly
    text = re.sub(r'[।]', '', text)

    # Remove extra whitespaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply the cleaning function to the 'Tweet' column
df_hin_train['Sentence'] = df_hin_train['Sentence'].apply(clean_hindi_text)

# Display the DataFrame with the cleaned tweets
df_hin_train.head()

      Label                                           Sentence
0   neutral                              आप अपने हाथ भरे होंगे
1   neutral                        कि मैंने किया कि मैंने किया
2   neutral   तो चलो अपने कर्तव्यों के बारे में थोड़ा बात करें
3  surprise                                मेरे कर्तव्य ठीक है
4   neutral  अब आप एक पूरे डिवीजन का नेतृत्व करेंगे तो आप ब...

In [67]:
# Define your custom Hindi stopwords
hindi_stopwords = [
    'और', 'है','हैं', 'के','हूँ', 'से', 'में', 'को', 'किया', 'यह', 'मैं', 'ना', 
    'यहाँ', 'तक', 'रहा', 'जैसे', 'उन', 'आप', 'हम', 'हमें', 'थी', 'किसी', 
    'वह', 'कर', 'नहीं', 'बात', 'करना', 'बोला', 'कहा', 'क्यों', 'सकता', 
    'तो', 'होगा', 'होगी', 'तुम', 'इन', 'जाना', 'चाहिए', 'लेकिन', 'अगर'
]

In [68]:
df_hin_train

         Label                                           Sentence
0      neutral                              आप अपने हाथ भरे होंगे
1      neutral                        कि मैंने किया कि मैंने किया
2      neutral   तो चलो अपने कर्तव्यों के बारे में थोड़ा बात करें
3     surprise                                मेरे कर्तव्य ठीक है
4      neutral  अब आप एक पूरे डिवीजन का नेतृत्व करेंगे तो आप ब...
...        ...                                                ...
7995       joy        अधिक लंदन नहींनहीं रोम विनय ओहओह बार्सिलोना
7996     anger  ठीक है क्या आप बस एक सेकंड के लिए बात बंद कर स...
7997     anger                                                 कब
7998   neutral                                 मैं ठीक नहीं जानता
7999   sadness  ओह अच्छी तरह से मैं उस क्षण आने तक चंडलर बिंंग...

[8000 rows x 2 columns]

In [69]:
import pandas as pd
import re

def remove_hindi_stopwords(text):
    # Remove special characters
    text = re.sub(r'[^(\u0900-\u097F\s)]', '', text)
    # Split the text into words
    words = text.split()
    # Remove stopwords
    filtered_words = [word for word in words if word not in hindi_stopwords]
    # Join the words back into a string
    return ' '.join(filtered_words)

# Apply the function to the 'Tweet' column
df_hin_train['Sentence'] = df_hin_train['Sentence'].apply(remove_hindi_stopwords)

# Display the DataFrame with the filtered tweets
df_hin_train.head()

      Label                                           Sentence
0   neutral                                 अपने हाथ भरे होंगे
1   neutral                                  कि मैंने कि मैंने
2   neutral                 चलो अपने कर्तव्यों बारे थोड़ा करें
3  surprise                                   मेरे कर्तव्य ठीक
4   neutral  अब एक पूरे डिवीजन का नेतृत्व करेंगे बहुत सारे ...

In [70]:
!pip install stanza

Requirement already satisfied: stanza in e:\conda\lib\site-packages (1.9.2)
Requirement already satisfied: emoji in e:\conda\lib\site-packages (from stanza) (2.13.2)
Requirement already satisfied: numpy in e:\conda\lib\site-packages (from stanza) (1.26.4)
Requirement already satisfied: protobuf>=3.15.0 in e:\conda\lib\site-packages (from stanza) (3.20.3)
Requirement already satisfied: requests in e:\conda\lib\site-packages (from stanza) (2.32.2)
Requirement already satisfied: networkx in e:\conda\lib\site-packages (from stanza) (3.2.1)
Requirement already satisfied: torch>=1.3.0 in e:\conda\lib\site-packages (from stanza) (2.4.1)
Requirement already satisfied: tqdm in e:\conda\lib\site-packages (from stanza) (4.66.4)
Requirement already satisfied: filelock in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (4.11.0)
Requirement already satisfied: sympy in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (1.12)
Requirement already satisfied: jinja2 in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (3.1.4)
Requirement already satisfied: fsspec in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (2024.3.1)
Requirement already satisfied: setuptools in e:\conda\lib\site-packages (from torch>=1.3.0->stanza) (69.5.1)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\conda\lib\site-packages (from requests->stanza) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in e:\conda\lib\site-packages (from requests->stanza) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\conda\lib\site-packages (from requests->stanza) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in e:\conda\lib\site-packages (from requests->stanza) (2024.6.2)
Requirement already satisfied: colorama in e:\conda\lib\site-packages (from tqdm->stanza) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in e:\conda\lib\site-packages (from jinja2->torch>=1.3.0->stanza) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in e:\conda\lib\site-packages (from sympy->torch>=1.3.0->stanza) (1.3.0)

In [71]:
import stanza

# Download Hindi language model
stanza.download('hi')

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json:   0%|   …

2024-10-24 14:46:56 INFO: Downloaded file to C:\Users\Harsha\stanza_resources\resources.json
2024-10-24 14:46:56 INFO: Downloading default packages for language: hi (Hindi) ...
2024-10-24 14:46:57 INFO: File exists: C:\Users\Harsha\stanza_resources\hi\default.zip
2024-10-24 14:46:59 INFO: Finished downloading models and saved to C:\Users\Harsha\stanza_resources

In [ ]:
import pandas as pd
import stanza

# Initialize the Hindi NLP pipeline
stanza.download('hi')  # Download the Hindi model
nlp = stanza.Pipeline('hi')

# Example DataFrame

def lemmatize_hindi(text):
    # Process the text with Stanza
    doc = nlp(text)
    # Get lemmas for each token
    lemmas = [word.lemma for sent in doc.sentences for word in sent.words]
    # Join the lemmas back into a string
    return ' '.join(lemmas)

# Apply the lemmatization function to the 'Tweet' column
df_hin_train['Sentence'] = df_hin_train['Sentence'].apply(lemmatize_hindi)

# Display the DataFrame with the lemmatized tweets
df_hin_train

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json:   0%|   …

2024-10-24 14:46:59 INFO: Downloaded file to C:\Users\Harsha\stanza_resources\resources.json
2024-10-24 14:46:59 INFO: Downloading default packages for language: hi (Hindi) ...
2024-10-24 14:46:59 INFO: File exists: C:\Users\Harsha\stanza_resources\hi\default.zip
2024-10-24 14:47:01 INFO: Finished downloading models and saved to C:\Users\Harsha\stanza_resources
2024-10-24 14:47:01 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json:   0%|   …

2024-10-24 14:47:01 INFO: Downloaded file to C:\Users\Harsha\stanza_resources\resources.json
2024-10-24 14:47:02 INFO: Loading these models for language: hi (Hindi):
=============================
| Processor | Package       |
-----------------------------
| tokenize  | hdtb          |
| pos       | hdtb_charlm   |
| lemma     | hdtb_nocharlm |
| depparse  | hdtb_charlm   |
=============================

2024-10-24 14:47:02 INFO: Using device: cpu
2024-10-24 14:47:02 INFO: Loading: tokenize
E:\conda\Lib\site-packages\stanza\models\tokenization\trainer.py:82: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 14:47:02 INFO: Loading: pos
E:\conda\Lib\site-packages\stanza\models\pos\trainer.py:139: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
E:\conda\Lib\site-packages\stanza\models\common\pretrain.py:56: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(self.filename, lambda storage, loc: storage)
E:\conda\Lib\site-packages\stanza\models\common\char_model.py:271: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(filename, lambda storage, loc: storage)
2024-10-24 14:47:02 INFO: Loading: lemma
E:\conda\Lib\site-packages\stanza\models\lemma\trainer.py:239: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 14:47:04 INFO: Loading: depparse
E:\conda\Lib\site-packages\stanza\models\depparse\trainer.py:194: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-10-24 14:47:04 INFO: Done loading processors!

In [ ]:
df_hin_train.isnull().any()

In [ ]:
df_hin_train_1 = pd.get_dummies(df_hin_train['Label'])
df_hin_train_1.head()

In [ ]:
df_hin_train_0 = df_hin_train.copy()
df_hin_train_0.drop(columns=['Label'], inplace = True)
df_hin_train_main = pd.concat([df_hin_train_0, df_hin_train_1], axis=1)
df_hin_train_main.head()

In [ ]:
df_hin_train_main.to_csv('stemmed_hindi.csv', index=False)

In [ ]:
from IPython.display import FileLink
FileLink('stemmed_hindi.csv')

In [ ]:
df_spa_train.to_csv('stemmed_spanish.csv', index=False)

In [ ]:
FileLink('stemmed_spanish.csv')

In [ ]:
df_eng_train.to_csv('stemmed_english.csv', index=False)

In [ ]:
FileLink('stemmed_english.csv')

In [ ]:
df_tw_train_main.to_csv('stemmed_eng.csv', index=False)

In [ ]:
FileLink('stemmed_eng.csv')