In [ ]:
!pip install datasets

Collecting datasets
  Downloading datasets-3.1.0-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from datasets) (3.16.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (17.0.0)
Collecting dill<0.3.9,>=0.3.0 (from datasets)
  Downloading dill-0.3.8-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.10/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.10/dist-packages (from datasets) (4.66.6)
Collecting xxhash (from datasets)
  Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting multiprocess<0.70.17 (from datasets)
  Downloading multiprocess-0.70.16-py310-none-any.whl.metadata (7.2 kB)
Collecting fsspec<=2024.9.0,>=2023.1.0 (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets)
  Downloading fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.10/dist-packages (from datasets) (3.10.10)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.10/dist-packages (from datasets) (0.26.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (1.17.1)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.32.2->datasets) (2024.8.30)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.10/dist-packages (from yarl<2.0,>=1.12.0->aiohttp->datasets) (0.2.0)
Downloading datasets-3.1.0-py3-none-any.whl (480 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 480.6/480.6 kB 19.8 MB/s eta 0:00:00
Downloading dill-0.3.8-py3-none-any.whl (116 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 9.4 MB/s eta 0:00:00
Downloading fsspec-2024.9.0-py3-none-any.whl (179 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.3/179.3 kB 11.6 MB/s eta 0:00:00
Downloading multiprocess-0.70.16-py310-none-any.whl (134 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 7.7 MB/s eta 0:00:00
Downloading xxhash-3.5.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (194 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 12.0 MB/s eta 0:00:00
Installing collected packages: xxhash, fsspec, dill, multiprocess, datasets
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2024.10.0
    Uninstalling fsspec-2024.10.0:
      Successfully uninstalled fsspec-2024.10.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.
Successfully installed datasets-3.1.0 dill-0.3.8 fsspec-2024.9.0 multiprocess-0.70.16 xxhash-3.5.0

In [ ]:
from datasets import load_dataset
spanish_twitter_dataset = load_dataset("SemEvalWorkshop/sem_eval_2018_task_1", "subtask5.spanish")
spanish_twitter_dataset

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sem_eval_2018_task_1.py:   0%|          | 0.00/6.29k [00:00<?, ?B/s]

The repository for SemEvalWorkshop/sem_eval_2018_task_1 contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/SemEvalWorkshop/sem_eval_2018_task_1.
You can avoid this prompt in future by passing the argument `trust_remote_code=True`.

Do you wish to run the custom code? [y/N] y

Downloading data:   0%|          | 0.00/5.98M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3561 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2854 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/679 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['ID', 'Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
        num_rows: 3561
    })
    test: Dataset({
        features: ['ID', 'Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
        num_rows: 2854
    })
    validation: Dataset({
        features: ['ID', 'Tweet', 'anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust'],
        num_rows: 679
    })
})

In [ ]:
import pandas as pd
df_spanish_train = pd.DataFrame(spanish_twitter_dataset['train'])
df_spanish_train.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-01643,@aliciaenp Ajajjaa somos del clan twitteras pe...,False,False,False,False,True,False,False,False,False,False,False
1,2018-Es-05142,@AwadaNai la mala suerte del gato fichame la c...,False,False,False,True,False,False,False,True,False,False,False
2,2018-Es-05379,@audiomano A mí tampoco me agrado mucho eso. E...,True,False,False,False,False,False,False,False,False,False,False
3,2018-Es-00208,Para llevar a los bebes de un lugar a otro deb...,False,False,False,False,True,False,False,False,False,False,False
4,2018-Es-01385,@DalasReview me encanta la terrible hipocresia...,True,False,True,False,False,False,False,False,False,False,False

In [ ]:
import pandas as pd
df_spanish_test = pd.DataFrame(spanish_twitter_dataset['test'])
df_spanish_test.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-07180,@Reforma QEPD 😢 Mis condolencias para sus fami...,False,False,False,False,False,False,False,False,True,False,False
1,2018-Es-00392,@Mubrutico @AlvaroVadin @aracnoideo Estoy enfa...,True,False,False,False,False,False,False,False,False,False,False
2,2018-Es-06102,@jotajordi13 @somhiserem @jmbartomeu Que estas...,True,False,False,False,False,False,False,False,False,False,False
3,2018-Es-05390,"""Tienes esa sonrisa que me gustaría ver cada d...",False,False,False,False,True,True,False,False,False,False,False
4,2018-Es-00153,Q horrible es querer dormir y no poder dormir ...,True,False,False,False,False,False,False,True,True,False,False

In [ ]:
import pandas as pd
df_spanish_validate = pd.DataFrame(spanish_twitter_dataset['validation'])
df_spanish_validate.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-06697,No me pienso perder la pelea de McGregor contr...,False,True,False,False,False,False,False,False,False,False,False
1,2018-Es-05385,Yo preocupada pensando que mi papá ya había ll...,False,True,False,True,False,False,False,False,False,False,False
2,2018-Es-03777,Pucha ya no me sirven todos los carros a Rondi...,False,False,False,False,True,False,False,False,False,False,False
3,2018-Es-02175,"Si estar contigo es un delito, hago cien años ...",False,False,False,False,True,True,False,False,False,False,False
4,2018-Es-00726,@macacifuentesC @sergmujica Perfect... Y de un...,False,False,True,False,False,False,False,False,False,False,False

In [ ]:
#combining spanish dataset (train , test and validation)
df_spanish_combined = pd.concat([df_spanish_train, df_spanish_test, df_spanish_validate])

In [ ]:
df_spanish_combined.head()

,ID,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,2018-Es-01643,@aliciaenp Ajajjaa somos del clan twitteras pe...,False,False,False,False,True,False,False,False,False,False,False
1,2018-Es-05142,@AwadaNai la mala suerte del gato fichame la c...,False,False,False,True,False,False,False,True,False,False,False
2,2018-Es-05379,@audiomano A mí tampoco me agrado mucho eso. E...,True,False,False,False,False,False,False,False,False,False,False
3,2018-Es-00208,Para llevar a los bebes de un lugar a otro deb...,False,False,False,False,True,False,False,False,False,False,False
4,2018-Es-01385,@DalasReview me encanta la terrible hipocresia...,True,False,True,False,False,False,False,False,False,False,False

In [ ]:
df_spa_comb = df_spanish_combined.drop(columns=['ID'])
df_spa_comb.head()
df_spa_comb.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7094 entries, 0 to 678
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tweet         7094 non-null   object
 1   anger         7094 non-null   bool
 2   anticipation  7094 non-null   bool
 3   disgust       7094 non-null   bool
 4   fear          7094 non-null   bool
 5   joy           7094 non-null   bool
 6   love          7094 non-null   bool
 7   optimism      7094 non-null   bool
 8   pessimism     7094 non-null   bool
 9   sadness       7094 non-null   bool
 10  surprise      7094 non-null   bool
 11  trust         7094 non-null   bool
dtypes: bool(11), object(1)
memory usage: 187.0+ KB

In [ ]:
!pip install deep-translator

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.10/dist-packages (from deep-translator) (4.12.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.10/dist-packages (from deep-translator) (2.32.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.6)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2024.8.30)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.3/42.3 kB 2.6 MB/s eta 0:00:00
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4

In [ ]:
!pip install google-cloud-translate

Requirement already satisfied: google-cloud-translate in /usr/local/lib/python3.10/dist-packages (3.17.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-translate) (2.19.2)
Requirement already satisfied: google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1 in /usr/local/lib/python3.10/dist-packages (from google-cloud-translate) (2.27.0)
Requirement already satisfied: google-cloud-core<3.0.0dev,>=1.4.4 in /usr/local/lib/python3.10/dist-packages (from google-cloud-translate) (2.4.1)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.10/dist-packages (from google-cloud-translate) (1.25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2 in /usr/local/lib/python3.10/dist-packages (from google-cloud-translate) (4.25.5)
Requirement already satisfied: grpc-google-iam-v1<1.0.0dev,>=0.12.4 in /usr/local/lib/python3.10/dist-packages (from google-cloud-translate) (0.13.1)
Requirement already satisfied: googleapis-common-protos<2.0.dev0,>=1.56.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-translate) (1.66.0)
Requirement already satisfied: requests<3.0.0.dev0,>=2.18.0 in /usr/local/lib/python3.10/dist-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-translate) (2.32.3)
Requirement already satisfied: grpcio<2.0dev,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-translate) (1.67.1)
Requirement already satisfied: grpcio-status<2.0.dev0,>=1.33.2 in /usr/local/lib/python3.10/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-translate) (1.62.3)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1->google-cloud-translate) (5.5.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1->google-cloud-translate) (0.4.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/dist-packages (from google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1->google-cloud-translate) (4.9)
Requirement already satisfied: pyasn1<0.7.0,>=0.4.6 in /usr/local/lib/python3.10/dist-packages (from pyasn1-modules>=0.2.1->google-auth!=2.24.0,!=2.25.0,<3.0.0dev,>=2.14.1->google-cloud-translate) (0.6.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-translate) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-translate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-translate) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0.dev0,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-cloud-translate) (2024.8.30)

In [ ]:
from deep_translator import GoogleTranslator
import pandas as pd
import time


# Batch processing function
def batch_translate(texts, batch_size=100):
    translated = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i+batch_size]
        try:
            # Translate the batch
            translated_batch = [GoogleTranslator(source='es', target='en').translate(text) for text in batch]
            translated.extend(translated_batch)
        except Exception as e:
            print(f"Error in batch {i // batch_size}: {e}")
            translated.extend(["Error"] * len(batch))  # Fill with placeholder if batch fails
            time.sleep(5)  # Avoid rate limit
        print(f"Translated up to row {min(i + batch_size, len(texts))} out of {len(texts)}")
    return translated

# Apply batch translation
df1['Tweet'] = batch_translate(df1['Tweet'].tolist())

# Save to CSV
df1.to_csv('translated_spa.csv', index=False)
print("Translation completed and saved to 'translated_spa.csv'")

Translated up to row 100 out of 7094
Translated up to row 200 out of 7094
Translated up to row 300 out of 7094
Translated up to row 400 out of 7094
Translated up to row 500 out of 7094
Translated up to row 600 out of 7094
Translated up to row 700 out of 7094
Translated up to row 800 out of 7094
Translated up to row 900 out of 7094
Translated up to row 1000 out of 7094
Translated up to row 1100 out of 7094
Translated up to row 1200 out of 7094
Translated up to row 1300 out of 7094
Translated up to row 1400 out of 7094
Translated up to row 1500 out of 7094
Translated up to row 1600 out of 7094
Translated up to row 1700 out of 7094
Translated up to row 1800 out of 7094
Translated up to row 1900 out of 7094
Translated up to row 2000 out of 7094
Translated up to row 2100 out of 7094
Translated up to row 2200 out of 7094
Translated up to row 2300 out of 7094
Translated up to row 2400 out of 7094
Translated up to row 2500 out of 7094
Translated up to row 2600 out of 7094
Translated up to row 2700 out of 7094
Translated up to row 2800 out of 7094
Translated up to row 2900 out of 7094
Translated up to row 3000 out of 7094
Translated up to row 3100 out of 7094
Translated up to row 3200 out of 7094
Translated up to row 3300 out of 7094
Translated up to row 3400 out of 7094
Translated up to row 3500 out of 7094
Translated up to row 3600 out of 7094
Translated up to row 3700 out of 7094
Translated up to row 3800 out of 7094
Translated up to row 3900 out of 7094
Translated up to row 4000 out of 7094
Translated up to row 4100 out of 7094
Translated up to row 4200 out of 7094
Translated up to row 4300 out of 7094
Translated up to row 4400 out of 7094
Translated up to row 4500 out of 7094
Translated up to row 4600 out of 7094
Translated up to row 4700 out of 7094
Translated up to row 4800 out of 7094
Translated up to row 4900 out of 7094
Translated up to row 5000 out of 7094
Translated up to row 5100 out of 7094
Translated up to row 5200 out of 7094
Translated up to row 5300 out of 7094
Translated up to row 5400 out of 7094
Translated up to row 5500 out of 7094
Translated up to row 5600 out of 7094
Translated up to row 5700 out of 7094
Translated up to row 5800 out of 7094
Translated up to row 5900 out of 7094
Translated up to row 6000 out of 7094
Translated up to row 6100 out of 7094
Translated up to row 6200 out of 7094
Translated up to row 6300 out of 7094
Translated up to row 6400 out of 7094
Translated up to row 6500 out of 7094
Translated up to row 6600 out of 7094
Translated up to row 6700 out of 7094
Translated up to row 6800 out of 7094
Translated up to row 6900 out of 7094
Translated up to row 7000 out of 7094
Translated up to row 7094 out of 7094
Translation completed and saved to 'translated_spa.csv'

In [ ]:
df1.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,@aliciaenp Ajajjaa we are from the lost twitte...,False,False,False,False,True,False,False,False,False,False,False
1,@AwadaNai the cat's bad luck check my face hel...,False,False,False,True,False,False,False,True,False,False,False
2,@audiomano I didn't like that either. Especial...,True,False,False,False,False,False,False,False,False,False,False
3,To take babies from one place to another we mu...,False,False,False,False,True,False,False,False,False,False,False
4,@DalasReview I love the terrible hypocrisy and...,True,False,True,False,False,False,False,False,False,False,False

In [ ]:

# Save the DataFrame to a CSV file
df1.to_csv('translated_spa.csv', index=False)

print("DataFrame has been saved to 'translated_text.csv'")

In [ ]:
from google.colab import files

# Download the CSV file
files.download('translated_spa.csv')

In [1]:
# prompt: mount drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
#Loading the hindi dataset
file_path  = '/content/drive/MyDrive/ML_sem2/output_combined_data_processed (1).csv'
df_hindi = pd.read_csv(file_path)
df_hindi["Label"].unique()
print(len(df_hindi))

8000

In [ ]:
# Specify the three emotion labels you want to keep
target_labels = ['anger','fear', 'sadness', 'surprise']

# Filter rows where emotion_label is one of the target labels
df2 = df_hindi[df_hindi['Label'].isin(target_labels)]

# Display the filtered DataFrame
print(df2)

         Label                                           Sentence
3     surprise                              मेरे कर्तव्य? ठीक है.
9         fear                             मैं तुमसे नहीं माँगता!
11    surprise                                             सचमुच?
13    surprise  लेकिन फिर कौन? मैं पिछले महीने के साथ बाहर गया...
14     sadness                       तुम्हें पता है? इसे भूल जाओ!
...        ...                                                ...
7991   sadness  ओह, बहुत जल्दी, बहुत चंमुन. यह बात ध्यान में र...
7993  surprise                           ओह नहीं! कहाँ? भी पेरिस?
7996     anger  ठीक है, क्या आप बस एक सेकंड के लिए बात बंद कर ...
7997     anger                                                कब?
7999   sadness  ओह, अच्छी तरह से मैं उस क्षण आने तक चंडलर बिंं...

[2633 rows x 2 columns]

In [ ]:
#joy columns
target_labels = ['joy']

# Filter rows where emotion_label is one of the target labels
df2_1 = df_hindi[df_hindi['Label'].isin(target_labels)]

# Display the filtered DataFrame
print(df2_1)

     Label                                           Sentence
22     joy                                  मैं कभी करता हूँ।
30     joy                                 तुम धोखे में पड़ो!
32     joy                                  उम्-अम्, हाँ सही!
43     joy                                               हाय!
49     joy  ठीक है, महिला मैं बातचीत के साथ बहुत कठिन था, ...
...    ...                                                ...
7948   joy  मैं तुम्हें आज रात के भोजन के लिए बाहर ले जा र...
7949   joy  मैंने इस जगह को पाया जो मज़ेरालेट की सबसे बड़ी...
7951   joy                          उनका स्वाद बहुत अच्छा है।
7990   joy  ठीक है! मैं सिर्फ सोचता हूँ कि यह बहुत जल्दी ह...
7995   joy  अधिक लंदन? नहीं-नहीं, रोम? विनय? ओह-ओह, बार्सि...

[1414 rows x 2 columns]

In [ ]:
from deep_translator import GoogleTranslator
import pandas as pd
import time


# Batch translation function with progress tracking
def batch_translate(texts, batch_size=100):
    translated = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        try:
            # Translate the batch
            translated_batch = [GoogleTranslator(source='hi', target='en').translate(text) for text in batch]
            translated.extend(translated_batch)
        except Exception as e:
            print(f"Error in batch {i // batch_size}: {e}")
            translated.extend(["Error"] * len(batch))  # Fill with placeholder if batch fails
            time.sleep(5)  # Avoid rate limits

        # Print progress
        print(f"Translated up to row {min(i + batch_size, len(texts))} out of {len(texts)}")
    return translated

# Apply batch translation
df2_1['Sentence'] = batch_translate(df2_1['Sentence'].tolist())

# Save to CSV
df2_1.to_csv('translated_hin.csv', index=False)
print("Translation completed and saved to 'translated_hin.csv'")

Translated up to row 100 out of 1414
Translated up to row 200 out of 1414
Translated up to row 300 out of 1414
Translated up to row 400 out of 1414
Translated up to row 500 out of 1414
Translated up to row 600 out of 1414
Translated up to row 700 out of 1414
Translated up to row 800 out of 1414
Translated up to row 900 out of 1414
Translated up to row 1000 out of 1414
Translated up to row 1100 out of 1414
Translated up to row 1200 out of 1414
Translated up to row 1300 out of 1414
Translated up to row 1400 out of 1414
Translated up to row 1414 out of 1414
Translation completed and saved to 'translated_hin.csv'

<ipython-input-9-61a5c80aa87e>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2_1['Sentence'] = batch_translate(df2_1['Sentence'].tolist())

In [ ]:
from google.colab import files
df2_1.to_csv('translated_hin1.csv', index=False)
# Download the CSV file
files.download('translated_hin1.csv')

In [ ]:
from deep_translator import GoogleTranslator
import pandas as pd
import time


# Batch translation function with progress tracking
def batch_translate(texts, batch_size=100):
    translated = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        try:
            # Translate the batch
            translated_batch = [GoogleTranslator(source='hi', target='en').translate(text) for text in batch]
            translated.extend(translated_batch)
        except Exception as e:
            print(f"Error in batch {i // batch_size}: {e}")
            translated.extend(["Error"] * len(batch))  # Fill with placeholder if batch fails
            time.sleep(5)  # Avoid rate limits

        # Print progress
        print(f"Translated up to row {min(i + batch_size, len(texts))} out of {len(texts)}")
    return translated

# Apply batch translation
df2['Sentence'] = batch_translate(df2['Sentence'].tolist())

# Save to CSV
df2.to_csv('translated_text_hin.csv', index=False)
print("Translation completed and saved to 'translated_text_hin.csv'")

Translated up to row 100 out of 2633
Translated up to row 200 out of 2633
Translated up to row 300 out of 2633
Translated up to row 400 out of 2633
Translated up to row 500 out of 2633
Translated up to row 600 out of 2633
Translated up to row 700 out of 2633
Translated up to row 800 out of 2633
Translated up to row 900 out of 2633
Translated up to row 1000 out of 2633
Translated up to row 1100 out of 2633
Translated up to row 1200 out of 2633
Translated up to row 1300 out of 2633
Translated up to row 1400 out of 2633
Translated up to row 1500 out of 2633
Translated up to row 1600 out of 2633
Translated up to row 1700 out of 2633
Translated up to row 1800 out of 2633
Translated up to row 1900 out of 2633
Translated up to row 2000 out of 2633
Translated up to row 2100 out of 2633
Translated up to row 2200 out of 2633
Translated up to row 2300 out of 2633
Translated up to row 2400 out of 2633
Translated up to row 2500 out of 2633
Translated up to row 2600 out of 2633
Translated up to row 2633 out of 2633
Translation completed and saved to 'translated_text_hin.csv'

<ipython-input-8-42ebb7addd67>:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Sentence'] = batch_translate(df2['Sentence'].tolist())

In [ ]:
df2.head()

       Label                                           Sentence
3   surprise                                   My duties? Okay.
9       fear                                   I don't ask you!
11  surprise                                            Really?
13  surprise  But then who? The restaurant I went out with l...
14   sadness                          You know what? Forget it!

In [ ]:
from google.colab import files
# Download the CSV file
files.download('translated_text_hin.csv')

In [ ]:
import pandas as pd
#Loading the hindi dataset
file_path  = "C:\\Users\\Harsha\\Downloads\\translated_text_hin.csv"
df_hindi = pd.read_csv(file_path)
df_hindi["Label"].unique()
print(len(df_hindi))

2633

In [ ]:
import pandas as pd
#Loading the hindi dataset
file_path  = "C:\\Users\\Harsha\\Downloads\\translated_hin1.csv"
df_hindi_1 = pd.read_csv(file_path)
df_hindi_1["Label"].unique()
print(len(df_hindi_1))

1414

In [ ]:
df_hin = pd.concat([df_hindi, df_hindi_1])

In [ ]:
df_hin.head()

      Label                                           Sentence
0  surprise                                   My duties? Okay.
1      fear                                   I don't ask you!
2  surprise                                            Really?
3  surprise  But then who? The restaurant I went out with l...
4   sadness                          You know what? Forget it!

In [ ]:
df_hin = df_hin.rename(columns={'Sentence': 'text'})
df_hin = df_hin.rename(columns={'Label': 'Emotion'})

In [ ]:
# Count total float values in the entire DataFrame
total_float = df_hin.applymap(lambda x: isinstance(x, float)).sum().sum()
print(f"Total float values in the DataFrame: {total_float}")

Total float values in the DataFrame: 0

C:\Users\Harsha\AppData\Local\Temp\ipykernel_38752\558290020.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  total_float = df_hin.applymap(lambda x: isinstance(x, float)).sum().sum()

In [ ]:
# Count total NaN values in the entire DataFrame
total_nan = df_hin.isna().sum().sum()
print(f"Total NaN values in the DataFrame: {total_nan}")

Total NaN values in the DataFrame: 0

In [ ]:
import pandas as pd
#Loading the hindi dataset
file_path  = "C:\\Users\\Harsha\\Downloads\\translated_spa.csv"
df_spa = pd.read_csv(file_path)
#df_spa["Label"].unique()
print(len(df_spa))

7094

In [ ]:
df_spa.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,@aliciaenp Ajajjaa we are from the lost twitte...,False,False,False,False,True,False,False,False,False,False,False
1,@AwadaNai the cat's bad luck check my face hel...,False,False,False,True,False,False,False,True,False,False,False
2,@audiomano I didn't like that either. Especial...,True,False,False,False,False,False,False,False,False,False,False
3,To take babies from one place to another we mu...,False,False,False,False,True,False,False,False,False,False,False
4,@DalasReview I love the terrible hypocrisy and...,True,False,True,False,False,False,False,False,False,False,False

In [ ]:

emotion_columns_s = ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust']

In [ ]:
df_spa['Emotion'] = df_spa[emotion_columns_s].idxmax(axis=1)

In [ ]:
df_spa = df_spa[['Tweet', 'Emotion']]

In [ ]:
# Specify the three emotion labels you want to keep
target_labels = ['anger','fear', 'joy','sadness', 'surprise']

# Filter rows where emotion_label is one of the target labels
df_spa = df_spa[df_spa['Emotion'].isin(target_labels)]

# Display the filtered DataFrame
print(df_spa)

                                                  Tweet Emotion
0     @aliciaenp Ajajjaa we are from the lost twitte...     joy
1     @AwadaNai the cat's bad luck check my face hel...    fear
2     @audiomano I didn't like that either. Especial...   anger
3     To take babies from one place to another we mu...     joy
4     @DalasReview I love the terrible hypocrisy and...   anger
...                                                 ...     ...
7087                           CTM that make me laugh 😂     joy
7089  @tccharless -Danger at the wheel -Tec -Los San...    fear
7091  @kopexinfinity CONGRATULATIONS FER 💕 WHAT'S HA...     joy
7092  @PabloEmanuel299 I AM SORRY FOR MY CONFUSION W...   anger
7093  My niece saw the photo on the wall, the one wh...     joy

[5383 rows x 2 columns]

In [ ]:
df_spa = df_spa.rename(columns={'Tweet': 'text'})

In [ ]:
# Count total float values in the entire DataFrame
total_float = df_spa.applymap(lambda x: isinstance(x, float)).sum().sum()
print(f"Total float values in the DataFrame: {total_float}")

Total float values in the DataFrame: 0

C:\Users\Harsha\AppData\Local\Temp\ipykernel_38752\2181071195.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  total_float = df_spa.applymap(lambda x: isinstance(x, float)).sum().sum()

In [ ]:
# Count total NaN values in the entire DataFrame
total_nan = df_spa.isna().sum().sum()
print(f"Total NaN values in the DataFrame: {total_nan}")

Total NaN values in the DataFrame: 0

In [ ]:
import pandas as pd
#Loading the hindi dataset
file_path  = "C:\\Users\\Harsha\\Downloads\\stemmed_engp.csv"
df_eng0 = pd.read_csv(file_path)
#df_spa["Label"].unique()
print(len(df_eng0))

29999

In [ ]:
df_eng0.head()

,Unnamed: 0,text,anger,fear,joy,love,sadness,surprise
0,405147,feel like world dangerous band class rsswidget...,True,False,False,False,False,False
1,349563,stood front building feeling strange,False,True,False,False,False,False
2,304040,wasnt feeling completely inspired paper checke...,False,False,True,False,False,False
3,182895,building almost every level feeling little fru...,True,False,False,False,False,False
4,369139,ive got feeling feel like want paint wall go c...,True,False,False,False,False,False

In [ ]:
df_eng0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29999 entries, 0 to 29998
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  29999 non-null  int64
 1   text        29998 non-null  object
 2   anger       29999 non-null  bool
 3   fear        29999 non-null  bool
 4   joy         29999 non-null  bool
 5   love        29999 non-null  bool
 6   sadness     29999 non-null  bool
 7   surprise    29999 non-null  bool
dtypes: bool(6), int64(1), object(1)
memory usage: 644.6+ KB

In [ ]:
df_eng0 = df_eng0[df_eng0.iloc[:, 1:].any(axis=1)]

In [ ]:

emotion_columns_e = ['anger', 'fear', 'joy', 'love', 'sadness', 'surprise']

In [ ]:
df_eng0['Emotion'] = df_eng0[emotion_columns_e].idxmax(axis=1)

In [ ]:
df_eng0 = df_eng0[['text', 'Emotion']]

In [ ]:
import pandas as pd
#Loading the hindi dataset
file_path  = "C:\\Users\\Harsha\\Downloads\\stemmed_eng1p.csv"
df_eng1 = pd.read_csv(file_path)
#df_spa["Label"].unique()
print(len(df_eng1))

10983

In [ ]:
df_eng1.head()

,Tweet,anger,anticipation,disgust,fear,joy,love,optimism,pessimism,sadness,surprise,trust
0,worry payment problem may never joyce meyer,False,True,False,False,False,False,True,False,False,False,True
1,whatever decide make sure make,False,False,False,False,True,True,True,False,False,False,False
2,also help majority nfl coaching inept bill obr...,True,False,True,False,True,False,True,False,False,False,False
3,accept challenge literally even feel exhilarat...,False,False,False,False,True,False,True,False,False,False,False
4,roommate okay cant spell autocorrect,True,False,True,False,False,False,False,False,False,False,False

In [ ]:
df_eng1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10983 entries, 0 to 10982
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tweet         10958 non-null  object
 1   anger         10983 non-null  bool
 2   anticipation  10983 non-null  bool
 3   disgust       10983 non-null  bool
 4   fear          10983 non-null  bool
 5   joy           10983 non-null  bool
 6   love          10983 non-null  bool
 7   optimism      10983 non-null  bool
 8   pessimism     10983 non-null  bool
 9   sadness       10983 non-null  bool
 10  surprise      10983 non-null  bool
 11  trust         10983 non-null  bool
dtypes: bool(11), object(1)
memory usage: 203.9+ KB

In [ ]:

emotion_columns_e1 = ['anger', 'anticipation', 'disgust', 'fear', 'joy', 'love', 'optimism', 'pessimism', 'sadness', 'surprise', 'trust']

In [ ]:
df_eng1['Emotion'] = df_eng1[emotion_columns_e1].idxmax(axis=1)

In [ ]:
df_eng1 = df_eng1[['Tweet', 'Emotion']]

In [ ]:
df_eng1 = df_eng1.rename(columns={'Tweet': 'text'})

In [ ]:
df_eng = pd.concat([df_eng0, df_eng1])

In [ ]:
df_eng

                                                    text Emotion
0      feel like world dangerous band class rsswidget...   anger
1                   stood front building feeling strange    fear
2      wasnt feeling completely inspired paper checke...     joy
3      building almost every level feeling little fru...   anger
4      ive got feeling feel like want paint wall go c...   anger
...                                                  ...     ...
10978                   do not make angry id laugh tweet   anger
10979                     excited watch tonight come NSw     joy
10980   blah blah blah kyrie etc. leave boston real news   anger
10981                        wise never trust flock wolf   anger
10982  really flatter happy hear complement blog guy ...     joy

[40982 rows x 2 columns]

In [ ]:
# Count total float values in the entire DataFrame
total_float = df_eng.applymap(lambda x: isinstance(x, float)).sum().sum()
print(f"Total float values in the DataFrame: {total_float}")

Total float values in the DataFrame: 26

C:\Users\Harsha\AppData\Local\Temp\ipykernel_38752\1185785188.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  total_float = df_eng.applymap(lambda x: isinstance(x, float)).sum().sum()

In [ ]:
# Count total NaN values in the entire DataFrame
total_nan = df_eng.isna().sum().sum()
print(f"Total NaN values in the DataFrame: {total_nan}")

Total NaN values in the DataFrame: 26

In [ ]:
# Specify the three emotion labels you want to keep
target_labels = ['anger','fear', 'joy','sadness', 'surprise']

# Filter rows where emotion_label is one of the target labels
df_eng = df_eng[df_eng['Emotion'].isin(target_labels)]

# Display the filtered DataFrame
print(df_eng)

                                                    text Emotion
0      feel like world dangerous band class rsswidget...   anger
1                   stood front building feeling strange    fear
2      wasnt feeling completely inspired paper checke...     joy
3      building almost every level feeling little fru...   anger
4      ive got feeling feel like want paint wall go c...   anger
...                                                  ...     ...
10978                   do not make angry id laugh tweet   anger
10979                     excited watch tonight come NSw     joy
10980   blah blah blah kyrie etc. leave boston real news   anger
10981                        wise never trust flock wolf   anger
10982  really flatter happy hear complement blog guy ...     joy

[35891 rows x 2 columns]

In [ ]:
df = pd.concat([df_spa, df_hin, df_eng])

In [ ]:
df

                                                    text Emotion
0      @aliciaenp Ajajjaa we are from the lost twitte...     joy
1      @AwadaNai the cat's bad luck check my face hel...    fear
2      @audiomano I didn't like that either. Especial...   anger
3      To take babies from one place to another we mu...     joy
4      @DalasReview I love the terrible hypocrisy and...   anger
...                                                  ...     ...
10978                   do not make angry id laugh tweet   anger
10979                     excited watch tonight come NSw     joy
10980   blah blah blah kyrie etc. leave boston real news   anger
10981                        wise never trust flock wolf   anger
10982  really flatter happy hear complement blog guy ...     joy

[45321 rows x 2 columns]

In [ ]:
# Count total NaN values in the entire DataFrame
total_nan = df.isna().sum().sum()
print(f"Total NaN values in the DataFrame: {total_nan}")

Total NaN values in the DataFrame: 24

In [ ]:
df.describe()

                                  text Emotion
count                            45297   45321
unique                           44060       5
top     watch amazing lively broadcast     joy
freq                                41   16358

In [ ]:
import pandas as pd

# Check for rows where 'text' contains float values
float_rows = df[df['text'].apply(lambda x: isinstance(x, float))]

# Print rows with float values
print("Rows with float values in 'text' column:")
print(float_rows)

# Remove rows with float values from the DataFrame
df = df[~df['text'].apply(lambda x: isinstance(x, float))]

# Reset index after dropping rows (optional)
df.reset_index(drop=True, inplace=True)

# Display the cleaned DataFrame
print("\nCleaned DataFrame:")
print(df.head())

Rows with float values in 'text' column:
      text   Emotion
8817   NaN     anger
418    NaN      fear
1930   NaN       joy
3085   NaN      fear
4134   NaN       joy
4351   NaN       joy
5980   NaN       joy
6420   NaN       joy
7078   NaN       joy
7093   NaN   sadness
7342   NaN       joy
7386   NaN  surprise
8259   NaN   sadness
8482   NaN     anger
8606   NaN     anger
8974   NaN     anger
9140   NaN       joy
9418   NaN     anger
9847   NaN       joy
10505  NaN       joy
10527  NaN       joy
10654  NaN   sadness
10867  NaN     anger
10969  NaN     anger

Cleaned DataFrame:
                                                text Emotion
0  @aliciaenp Ajajjaa we are from the lost twitte...     joy
1  @AwadaNai the cat's bad luck check my face hel...    fear
2  @audiomano I didn't like that either. Especial...   anger
3  To take babies from one place to another we mu...     joy
4  @DalasReview I love the terrible hypocrisy and...   anger

In [ ]:
row_data = df.iloc[8817]
print(f"Data in row {8817}:")
print(row_data)

Data in row 8817:
text       Oh yes? Well when you learned to dance did you...
Emotion                                                  joy
Name: 8817, dtype: object

In [ ]:
import re

# Function to clean text
def clean_text(text):
    # Convert text to lowercase
    text = text.lower()

    # Remove URLs
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)

    # Remove email addresses
    text = re.sub(r'\S*@\S*\s?', '', text)

    # Remove mentions (@usernames)
    text = re.sub(r'@\w+', '', text)

    # Remove hashtags
    text = re.sub(r'#\w+', '', text)

    # Remove special characters and numbers, keep only letters
    text = re.sub(r'[^a-zA-Z\s]', '', text)

    # Remove extra whitespaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# Apply the cleaning function to the DataFrame
df['text'] = df['text'].apply(clean_text)

# View the cleaned DataFrame
df.head()

C:\Users\Harsha\AppData\Local\Temp\ipykernel_38752\2061640645.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df['text'].apply(clean_text)

                                                text Emotion
0  ajajjaa we are from the lost twitter clan for ...     joy
1        the cats bad luck check my face help me pls    fear
2  i didnt like that either especially since it w...   anger
3  to take babies from one place to another we mu...     joy
4  i love the terrible hypocrisy and double stand...   anger

In [ ]:
df

                                                    text Emotion
0      ajajjaa we are from the lost twitter clan for ...     joy
1            the cats bad luck check my face help me pls    fear
2      i didnt like that either especially since it w...   anger
3      to take babies from one place to another we mu...     joy
4      i love the terrible hypocrisy and double stand...   anger
...                                                  ...     ...
45292                   do not make angry id laugh tweet   anger
45293                     excited watch tonight come nsw     joy
45294    blah blah blah kyrie etc leave boston real news   anger
45295                        wise never trust flock wolf   anger
45296  really flatter happy hear complement blog guy ...     joy

[45297 rows x 2 columns]

In [ ]:
#stopwords
!pip install nltk
!pip install indic-nlp-library
!pip install stopwords
import nltk
nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

Requirement already satisfied: nltk in e:\conda\lib\site-packages (3.8.1)
Requirement already satisfied: click in e:\conda\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in e:\conda\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in e:\conda\lib\site-packages (from nltk) (2023.10.3)
Requirement already satisfied: tqdm in e:\conda\lib\site-packages (from nltk) (4.66.4)
Requirement already satisfied: colorama in e:\conda\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: indic-nlp-library in e:\conda\lib\site-packages (0.92)
Requirement already satisfied: sphinx-argparse in e:\conda\lib\site-packages (from indic-nlp-library) (0.5.2)
Requirement already satisfied: sphinx-rtd-theme in e:\conda\lib\site-packages (from indic-nlp-library) (2.0.0)
Requirement already satisfied: morfessor in e:\conda\lib\site-packages (from indic-nlp-library) (2.0.6)
Requirement already satisfied: pandas in e:\conda\lib\site-packages (from indic-nlp-library) (2.2.2)
Requirement already satisfied: numpy in e:\conda\lib\site-packages (from indic-nlp-library) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in e:\conda\lib\site-packages (from pandas->indic-nlp-library) (2023.3)
Requirement already satisfied: sphinx>=5.1.0 in e:\conda\lib\site-packages (from sphinx-argparse->indic-nlp-library) (7.3.7)
Requirement already satisfied: docutils>=0.19 in e:\conda\lib\site-packages (from sphinx-argparse->indic-nlp-library) (0.20.1)
Requirement already satisfied: sphinxcontrib-jquery<5,>=4 in e:\conda\lib\site-packages (from sphinx-rtd-theme->indic-nlp-library) (4.1)
Requirement already satisfied: six>=1.5 in e:\conda\lib\site-packages (from python-dateutil>=2.8.2->pandas->indic-nlp-library) (1.16.0)
Requirement already satisfied: sphinxcontrib-applehelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.2)
Requirement already satisfied: sphinxcontrib-devhelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.2)
Requirement already satisfied: sphinxcontrib-jsmath in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.1)
Requirement already satisfied: sphinxcontrib-htmlhelp>=2.0.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.0)
Requirement already satisfied: sphinxcontrib-serializinghtml>=1.1.9 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.1.10)
Requirement already satisfied: sphinxcontrib-qthelp in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.0.3)
Requirement already satisfied: Jinja2>=3.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.1.4)
Requirement already satisfied: Pygments>=2.14 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.15.1)
Requirement already satisfied: snowballstemmer>=2.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.2.0)
Requirement already satisfied: babel>=2.9 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.11.0)
Requirement already satisfied: alabaster~=0.7.14 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (0.7.16)
Requirement already satisfied: imagesize>=1.3 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (1.4.1)
Requirement already satisfied: requests>=2.25.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.32.2)
Requirement already satisfied: packaging>=21.0 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (23.2)
Requirement already satisfied: colorama>=0.4.5 in e:\conda\lib\site-packages (from sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in e:\conda\lib\site-packages (from Jinja2>=3.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in e:\conda\lib\site-packages (from requests>=2.25.0->sphinx>=5.1.0->sphinx-argparse->indic-nlp-library) (2024.6.2)
Requirement already satisfied: stopwords in e:\conda\lib\site-packages (1.0.1)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [ ]:
import pandas as pd
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize



# Load NLTK stopwords
stop_words = set(stopwords.words('english'))

# Define a function to remove stopwords
def remove_stopwords(sentence):
    words = word_tokenize(sentence)
    filtered = [word for word in words if word.lower() not in stop_words]
    return ' '.join(filtered)

# Apply the function to the 'text' column
df.loc[:, 'text'] = df['text'].apply(remove_stopwords)

# Display the DataFrame
print(df)

                                                    text Emotion
0             ajajjaa lost twitter clan important events     joy
1                      cats bad luck check face help pls    fear
2       didnt like either especially since theres excuse   anger
3      take babies one place another must sing songs ...     joy
4      love terrible hypocrisy double standards peopl...   anger
...                                                  ...     ...
45292                          make angry id laugh tweet   anger
45293                     excited watch tonight come nsw     joy
45294    blah blah blah kyrie etc leave boston real news   anger
45295                        wise never trust flock wolf   anger
45296  really flatter happy hear complement blog guy ...     joy

[45297 rows x 2 columns]

In [ ]:
df.head()

                                                text Emotion
0         ajajjaa lost twitter clan important events     joy
1                  cats bad luck check face help pls    fear
2   didnt like either especially since theres excuse   anger
3  take babies one place another must sing songs ...     joy
4  love terrible hypocrisy double standards peopl...   anger

In [ ]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Download required NLTK data
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')

# Example DataFrame

# Initialize WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

# Define a function to lemmatize text
def lemmatize_text(sentence):
    tokens = word_tokenize(sentence)  # Tokenize sentence
    lemmatized = [lemmatizer.lemmatize(word) for word in tokens]  # Lemmatize each token
    return ' '.join(lemmatized)  # Reconstruct the sentence

# Apply the lemmatization function to the DataFrame column
df['text'] = df['text'].apply(lemmatize_text)

# Display the DataFrame
print(df)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Harsha\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

                                                    text Emotion
0              ajajjaa lost twitter clan important event     joy
1                       cat bad luck check face help pls    fear
2        didnt like either especially since there excuse   anger
3      take baby one place another must sing song wan...     joy
4      love terrible hypocrisy double standard people...   anger
...                                                  ...     ...
45292                          make angry id laugh tweet   anger
45293                     excited watch tonight come nsw     joy
45294    blah blah blah kyrie etc leave boston real news   anger
45295                        wise never trust flock wolf   anger
45296  really flatter happy hear complement blog guy ...     joy

[45297 rows x 2 columns]

C:\Users\Harsha\AppData\Local\Temp\ipykernel_38752\373986445.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['text'] = df['text'].apply(lemmatize_text)

In [ ]:
df.to_csv('lemma_text.csv', index=False)
print("Translation completed and saved")

Translation completed and saved

In [ ]:
from IPython.display import FileLink
FileLink('lemma_text.csv')

C:\Users\Harsha\Downloads\lemma_text.csv

In [1]:
# prompt: mount drive

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
#Loading the hindi dataset
file_path  = '/content/drive/MyDrive/Untitled folder/lemma_text.csv'
df = pd.read_csv(file_path)
print(len(df))

45297

In [3]:
df.isnull()

        text  Emotion
0      False    False
1      False    False
2      False    False
3      False    False
4      False    False
...      ...      ...
45292  False    False
45293  False    False
45294  False    False
45295  False    False
45296  False    False

[45297 rows x 2 columns]

In [4]:
df.dropna()

                                                    text Emotion
0              ajajjaa lost twitter clan important event     joy
1                       cat bad luck check face help pls    fear
2        didnt like either especially since there excuse   anger
3      take baby one place another must sing song wan...     joy
4      love terrible hypocrisy double standard people...   anger
...                                                  ...     ...
45292                          make angry id laugh tweet   anger
45293                     excited watch tonight come nsw     joy
45294    blah blah blah kyrie etc leave boston real news   anger
45295                        wise never trust flock wolf   anger
45296  really flatter happy hear complement blog guy ...     joy

[45137 rows x 2 columns]

In [5]:
if df['Emotion'].isnull().any():
    print("NaN values found in Emotion column after mapping. Please check the mapping.")

In [6]:
label_mapping = {'anger': 0,'fear': 1,
                 'joy': 2,
                 'sadness': 3, 'surprise': 4}

# Using .loc to avoid SettingWithCopyWarning
df.loc[:, 'Emotion'] = df['Emotion'].map(label_mapping)

In [7]:
df

                                                    text Emotion
0              ajajjaa lost twitter clan important event       2
1                       cat bad luck check face help pls       1
2        didnt like either especially since there excuse       0
3      take baby one place another must sing song wan...       2
4      love terrible hypocrisy double standard people...       0
...                                                  ...     ...
45292                          make angry id laugh tweet       0
45293                     excited watch tonight come nsw       2
45294    blah blah blah kyrie etc leave boston real news       0
45295                        wise never trust flock wolf       0
45296  really flatter happy hear complement blog guy ...       2

[45297 rows x 2 columns]

In [8]:
!pip install transformers
from transformers import AutoModelForSequenceClassification, AutoTokenizer, Trainer, TrainingArguments
import torch
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset
import pandas as pd

# Split data into training and validation sets
train_texts, val_texts, train_labels, val_labels = train_test_split(
    df['text'].tolist(),
    df['Emotion'].tolist(),
    test_size=0.2,
    random_state=42
)

Requirement already satisfied: transformers in /usr/local/lib/python3.10/dist-packages (4.46.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.16.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.26.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2024.9.11)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.4.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /usr/local/lib/python3.10/dist-packages (from transformers) (0.20.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.66.6)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.10.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2024.8.30)

In [14]:
import numpy as np

# Check for NaN values in train_texts
nan_texts = [text for text in train_texts if isinstance(text, float) and np.isnan(text)]
if nan_texts:
    print("NaN values found in training data:", len(nan_texts), "NaN values found.")

In [13]:
# Convert to list if it's a Pandas Series or similar
if not isinstance(train_texts, list):
    train_texts = list(train_texts)

# Ensure all elements are strings
train_texts = [str(text) for text in train_texts if text is not None]

In [12]:
import numpy as np

# Check for NaN values in train_texts
nan_texts1 = [text for text in val_texts if isinstance(text, float) and np.isnan(text)]
if nan_texts1:
    print("NaN values found in val data:", len(nan_texts1), "NaN values found.")

In [11]:
# Convert to list if it's a Pandas Series or similar
if not isinstance(val_texts, list):
    val_texts = list(val_texts)

# Ensure all elements are strings
val_texts = [str(text) for text in val_texts if text is not None]

In [15]:
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from torch.utils.data import Dataset
import torch

# Load the tokenizer and model
model_name = "bert-base-uncased"  # Replace with a Spanish-specific model if desired
tokenizer = BertTokenizer.from_pretrained(model_name)
model = BertForSequenceClassification.from_pretrained(model_name, num_labels=5)  # 5 emotion labels
# Tokenization function
def tokenize_function(texts):
    return tokenizer(texts, padding=True, truncation=True, return_tensors="pt", max_length=512)
# Tokenize the training and validation texts
train_encodings = tokenize_function(train_texts)
val_encodings = tokenize_function(val_texts)
# Custom Dataset class
class EmotionDataset(Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        item = {key: val[idx].clone().detach() for key, val in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item
# Create the Dataset objects
train_dataset = EmotionDataset(train_encodings, train_labels)
val_dataset = EmotionDataset(val_encodings, val_labels)

# Define training arguments
training_args = TrainingArguments(
    output_dir="./results",
    num_train_epochs=5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir="./logs",
    eval_strategy="epoch",
    save_strategy="epoch",
)

# Create Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

# Train the model
trainer.train()

# Evaluate the model
eval_results = trainer.evaluate()
print(eval_results)
#0860061c9c63c88d713a4e8fcf51011aca94aa50

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.
wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize
wandb: Paste an API key from your profile and hit enter, or press ctrl+c to quit:

 ··········

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

{'eval_loss': 0.8875270485877991, 'eval_runtime': 26.3978, 'eval_samples_per_second': 343.211, 'eval_steps_per_second': 21.479, 'epoch': 5.0}

In [16]:
from sklearn.metrics import accuracy_score

#val_dataset = EmotionDataset(val_encodings, val_labels)
# Get predictions
predictions = trainer.predict(EmotionDataset(val_encodings, val_labels))

# Convert logits to predicted labels (if necessary)
predicted_labels = np.argmax(predictions.predictions, axis=1)

# Calculate accuracy
accuracy = accuracy_score(val_labels, predicted_labels)  # Ensure val_labels are defined
print("Manual Accuracy:", accuracy)

Manual Accuracy: 0.8347682119205299

In [17]:
# Save the model and tokenizer
output_dir = '/content/drive/MyDrive/Untitled folder'
model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)

('/content/drive/MyDrive/Untitled folder/tokenizer_config.json',
 '/content/drive/MyDrive/Untitled folder/special_tokens_map.json',
 '/content/drive/MyDrive/Untitled folder/vocab.txt',
 '/content/drive/MyDrive/Untitled folder/added_tokens.json')

In [18]:
# Zip the saved model directory
import shutil
shutil.make_archive("saved_model", 'zip', output_dir)

# Download the zip file
from google.colab import files
files.download("saved_model.zip")